sample-data/fiscal-years/fy1.json
*Purpose*
To fix the failure of the reference environment builds - see https://issues.folio.org/browse/FOLIO-1500 and https://issues.folio.org/browse/MODFUND-37
*Approach*
Removes the now unrecognised properties from the sample record.
May only be a temporary resolution if the {{period_start}} and {{period_end}} properties were intended to be still included in the schema. If they were intended to be removed, then this is a breaking compatibility change rather than a bug.
*Questions*
Were the properties intended to be removed?
=> Remove unrecognised properties from fiscal year sample record MODFUND-37

src/main/java/org/folio/rest/impl/GroupAPI.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/FundsTest.java
[MODFISTO-23](https://issues.folio.org/browse/MODFISTO-23) Define and implement group API
Rename `group` DB table to `groups` due to ParseException because `GROUP` is sql keyword and constructions like `group.jsonb` are invalid
<details>
<summary>Exception - click to expand</summary>
```
...
PostgresClient  parseQuery SELECT jsonb,id FROM diku_mod_finance_storage.group  WHERE to_tsvector('simple', f_unaccent(group.jsonb->>'name')) @@ replace((to_tsquery('simple', f_unaccent('''a''')))::text, '&', '<->')::tsquery LIMIT 10 OFFSET 0
...
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "." ". "" at line 1, column 46.
Was expecting one of:
<EOF> 
"AS" ...
"DO" ...
"ANY" ...
"KEY" ...
"PERCENT" ...
"END" ...
"JOIN" ...
"LEFT" ...
"CROSS" ...
"OPEN" ...
"FULL" ...
"TABLE" ... …
```
=> MODFISTO-23 Define and implement group API

pom.xml, ramls/finance-storage.raml, src/main/java/org/folio/rest/impl/FinanceStorageAPI.java, src/main/java/org/folio/rest/impl/FiscalYearAPI.java, src/main/java/org/folio/rest/impl/LedgerAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/java/org/folio/rest/persist/Tx.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/LedgerFYTest.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/java/org/folio/rest/utils/TestEntities.java
[MODFISTO-37](https://issues.folio.org/browse/MODFISTO-37) Update LedgerFY table
- creating `LedgerFY` records when new ledger or fiscal year is created
- deleting `LedgerFY` records when ledger or fiscal year is deleted (basically it is not included into story but had to be implemented to not complicate unit testing)
- generation of the `LedgerFY` records is done in java code to generate uuid for each record (generation on postgres is deprecated)
- new index for "periodEnd" is added to fiscal year table because the logic  searches for FYs by this criteria
=> MODFISTO-37 Update LedgerFY table

pom.xml, ramls/transaction.raml, src/main/java/org/folio/rest/impl/FundAPI.java, src/main/java/org/folio/rest/impl/LedgerAPI.java, src/main/java/org/folio/rest/impl/TenantReferenceAPI.java, src/main/java/org/folio/rest/impl/TransactionAPI.java, src/main/java/org/folio/rest/impl/TransactionSummaryAPI.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/java/org/folio/rest/transaction/AbstractTransactionHandler.java, src/main/java/org/folio/rest/transaction/AllOrNothingHandler.java, src/main/java/org/folio/rest/transaction/DefaultTransactionHandler.java, src/main/java/org/folio/rest/transaction/EncumbranceHandler.java, src/main/java/org/folio/rest/transaction/TransactionHandler.java, src/main/resources/data/order-transaction-summaries/order-transaction-summary.json, src/main/resources/data/transactions/allocation.json, src/main/resources/data/transactions/credit.json, src/main/resources/data/transactions/encumbrance.json, src/main/resources/data/transactions/payment.json, src/main/resources/data/transactions/transfer.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/impl/TenantSampleDataTest.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/java/org/folio/rest/impl/TransactionTest.java, src/test/java/org/folio/rest/impl/TransactionsSummariesTest.java
[MODFISTO-56](https://issues.folio.org/browse/MODFISTO-56) - We need to ensure that Either all transactions must be created(updated) or none of them before opening(closing) an order
- updated post transaction summary API, on conflict id do nothing
- implemented (all or nothing approach)(https://wiki.folio.org/display/FOLIJET/Finance+Data+Model#FinanceDataModel-%22AllorNothing%22Operations) for POST and PUT encumbrance
- made POST idempotent for encumbrance type
- added unique index on set of fields for transactions with Encumbrance type
- added `fromFundId` and `encumbrance` fields presence check.
- RMB updated to 28.1.0
Additionally
- removed tags from sample data
- Does this PR meet or exceed the …
=> MODFISTO-56 Support all-or-nothing operations for encumbrances by order

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
Not expecting an actual "review", but this requires an approval so that i can merge and proceed with the remaining steps.
=> MODFISTO-66 FOLIO-2358 manage container memory

src/main/resources/templates/db_scripts/migration/budgets.sql, src/main/resources/templates/db_scripts/schema.json
[MODFISTO-83](https://issues.folio.org/browse/MODFISTO-83) need to improve migration script to rename duplicates when migrate from non-unique indexes to unique one for budget@name.
- add suffix with random number (e.g. newBudgetName = oldName + randomNumber) …
=> MODFISTO-83 Migration script improvement to support transition of non-unique index to unique one

src/main/java/org/folio/dao/ledgerfy/LedgerFiscalYearPostgresDAO.java, src/main/resources/templates/db_scripts/migration/pending_payment_cross_module.ftl, src/main/resources/templates/db_scripts/migration/rename_ledger_fy_table.ftl, src/main/resources/templates/db_scripts/schema.json, src/main/resources/templates/db_scripts/transactions.sql
[MODFISTO-110](https://issues.folio.org/browse/MODFISTO-111) Too many differences between foreign keys and indexes due to the renaming of the ledgerFy table
- revert table renaming
- changed the ledgerFy table name to lower case.
- update fromModuleVersion …
=> MODFISTO-110 mod-finance-storage: Update to RMB v30.0.2

pom.xml, src/main/resources/templates/db_scripts/schema.json
[MODFISTO-117](https://issues.folio.org/browse/MODFISTO-117)
- revert ledgerFY table renaming
- update unique index definition for ledgerFY table
- upgrade to RMB 30.1.0 …
=> MODFISTO-117 Index not being created during migration from FameFlower-Goldenrod

src/main/java/org/folio/service/transactions/EncumbranceAllOrNothingService.java, src/test/java/org/folio/rest/impl/EncumbrancesTest.java
[MODFISTO-118](https://issues.folio.org/browse/MODFISTO-118)
- enable calculations when encumbrance status has not been changed upon update …
=> MODFISTO-118 Budges is not updated if encumbrance status has not been changed

pom.xml
[MODFISTO-126](https://issues.folio.org/browse/MODFISTO-126)
After upgrade mod-finance-storage we get error during order approve "PgException: record "new" has no field "encumbrance_sourcepurchaseorderid""
- Rollback rmb to 30.2.0
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> [MODFISTO-126] Rollback rmb to 30.2.0

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
[MODFISTO-222](https://issues.folio.org/browse/MODFISTO-222)
- do not create budgets for inactive funds
- add rollover error when try to create encumbrance for non-existent budget
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> MODFISTO-222 Budget created for inactive fund

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql, src/main/resources/templates/db_scripts/migration/pending_payment_cross_module.ftl
[MODFISTO-215](https://issues.folio.org/browse/MODFISTO-215)
See _Analysis_ in [MODFISTO-215](https://issues.folio.org/browse/MODFISTO-215).
Is it possible to convert all Postgres scripts creating new records into Java ? It would be a cleaner way to resolve the constraint introduced by Pgpool-II, although it might lead to performance issues.
With mod-finance-storage 4.2.2, the ledgerfy table is not updated when an invoice is created with a fiscal year that does not specify a currency. This leads to an error in the recalculate_totals() function. It happens when enabling the module with loadSample=true (this was needed to test pending_payment_cross_module.ftl).
- Does this PR meet or exceed the …
=> [MODFISTO-215] Avoid using uuid_generate_v4()

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql, src/main/resources/templates/db_scripts/schema.json
…e with initialAllocation = 0
While it's helpful for reviewers to help identify …
=> [MODFISTO-247] - Rollover errors when at least 1 order has encumbrance with initialAllocation = 0

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
[MODFISTO-247](https://issues.folio.org/browse/MODFISTO-247)
Recreate encumbrances with 0 amounts during rollover (otherwise editing order amounts fails after rollover). …
=> [MODFISTO-247] Recreate encumbrances with 0 amounts during rollover

src/main/java/org/folio/dao/transactions/BaseTemporaryTransactionsDAO.java, src/main/java/org/folio/dao/transactions/TemporaryTransactionDAO.java, src/main/java/org/folio/service/transactions/AllOrNothingTransactionService.java
[MODFISTO-293](https://issues.folio.org/browse/MODFISTO-293) - Error All expected transactions already processed
When a single transaction fails in a set of transactions with a summary, the summary will never be able to finish successfully, and typically the calling process will give up on the whole operation. So temporary transactions have to be removed, otherwise they will be taken into account the next time a user tries using a transaction summary on the same order/invoice.
We assume one thing: that a calling process will not try to fix a transaction after an error and continue creating or updating transactions for a given summary. There is nothing like that in FOLIO, and it would be surprising even from an API-using external program.
Eventually we should use unique summary ids, and …
=> [MODFISTO-293] Delete temp transactions after a failure

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
https://issues.folio.org/browse/MODFIN-233
Fixed an issue with id collisions for rollover transfer transactions.
Any unhandled exceptions in budget_encumbrances_rollover function will now be saved to rollover error table.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> MODFIN-233 - fix rollover id collision and save script errors

src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/rest/persist/DBClientFactory.java, src/main/java/org/folio/rest/persist/HelperUtils.java, src/main/java/org/folio/service/transactions/AllOrNothingTransactionService.java, src/main/java/org/folio/service/transactions/EncumbranceService.java, src/main/java/org/folio/service/transactions/PaymentCreditService.java, src/main/java/org/folio/service/transactions/PendingPaymentService.java, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/service/transactions/EncumbranceServiceTest.java
=> [MODFISTO-328] - Encumbrance orderStatus is wrong after closing an order with a paid or approved invoice

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
=> MODFISTO-325 fixed encumbrance status after rollover

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
Automate the routine work of moving planned budgets into current budgets after financial rollover.
[MODFISTO-338](https://issues.folio.org/browse/MODFISTO-338)
Tested with karate. [Link to PR](https://github.com/folio-org/folio-integration-tests/pull/690) …
=> [MODFISTO-338] Update planned budget status to active during FY rollover

README.md, descriptors/DeploymentDescriptor-template.json
Add pointers to relevant information for this module and remove mentions of embed_postgres=true which was removed in RMB 32.2.0.
=> Pointers in README; embed_postgres no more

src/main/java/org/folio/dao/rollover/RolloverBudgetDAO.java, src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql, src/test/java/org/folio/dao/rollover/RolloverBudgetDAOTest.java
https://issues.folio.org/browse/FAT-3002
Karate test failed due to new logic connected with Preview functionality in case when rollover script not creating any new budgets during rollover process. 
This PR contains fix for the mentioned scenario
Screen from Karate:
=> [MODFISTO-318] Fix scenario when new budgets not created during rollover process

src/main/java/org/folio/dao/rollover/RolloverBudgetDAO.java, src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
https://issues.folio.org/browse/MODFIN-256
https://issues.folio.org/browse/MODFISTO-318
Update references to acq-models shcema to support:
- filtering rollover logs by ledger id
- provide fund details into rollover budgets response to reduce amount of UI calls
- provide expense class detatils into rollover budgets response that necessary in the final csv file
Update Rollover script to populate fund details in Rollover budgets API response (common Budgets API response not affected)
Corresponding Karate PR: https://github.com/folio-org/folio-integration-tests/pull/724/files
=> [MODFIN-256]. Define and implement Business API : Ledger Rollover Budgets [Part 2]

src/main/resources/templates/db_scripts/ledger_rollover_log_view.sql
https://issues.folio.org/browse/MODFIN-277
Add ledgerId in Rollover Logs API response.
Corresponding schema has been changed in scope of commit: https://github.com/folio-org/acq-models/pull/399/commits/abd0b01876321d64e62e07a5d421f4d18de05dfe 
and updated reference in finance-storage to the latest acq models in previous PRs
=> [MODFIN-277]. Add support to filter by ledger for Rollover Logs API

src/main/java/org/folio/dao/budget/BudgetExpenseClassDAOImpl.java, src/main/java/org/folio/service/budget/RolloverBudgetExpenseClassTotalsService.java
After financial rollover some fields(expense class code, expense class status) didn't show in rollover logs
[MODFISTO-362](https://issues.folio.org/browse/MODFISTO-362)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> [MODFISTO-362] Expense class code and status are not shown in test rollover results .csv file

scripts/fix_lotus_encumbrances/fix_lotus_encumbrances.py
[MODFISTO-367](https://issues.folio.org/browse/MODFISTO-367) - Encumbrance script: avoid requesting too many orders at once
Fixed `get_by_chunks()` as it would fail for large amounts of orders. `totalRecords` is not always accurate so it's better to not rely on it.
Ideally, all the PRs involved in …
=> [MODFISTO-367] Do not rely on totalRecords

src/main/java/org/folio/dao/summary/BaseTransactionSummaryDAO.java, src/main/java/org/folio/dao/summary/TransactionSummaryDao.java, src/main/java/org/folio/dao/transactions/BaseTemporaryTransactionsDAO.java, src/main/java/org/folio/dao/transactions/TemporaryEncumbranceTransactionDAO.java, src/main/java/org/folio/dao/transactions/TemporaryTransactionDAO.java, src/main/java/org/folio/service/summary/AbstractTransactionSummaryService.java, src/main/java/org/folio/service/summary/TransactionSummaryService.java, src/main/java/org/folio/service/transactions/AllOrNothingTransactionService.java, src/main/java/org/folio/service/transactions/TemporaryTransactionService.java, src/test/java/org/folio/service/transactions/EncumbranceServiceTest.java
https://issues.folio.org/browse/MODFISTO-377
We use SELECT FOR UPDATE locking on summary table by summaryId.
In this case requests to create temp transaction and get temp transaction count for the same summaryId
will be executed only by a single thread by the single instance of the module.
The other thread will wait until DB Lock is released when the connection is closed.
Method {@link org.folio.rest.persist.PostgresClient#withConn(Function)} closes connection after executing.
=> [MODFISTO-377]. Replace Vertx shared lock with DB lock to increase stability working with transactions

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, ramls/budget.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODFISTO-392 Use GitHub Workflows api-lint and api-schema-lint and api-doc

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql, src/main/resources/templates/db_scripts/schema.json
Before introducing rollover preview flow chaining run common rollover was resolving and correctly calculating encumbrances amount. Cross ledger chainging functionality doesn't work after introducing the feature. The PR aimed to fix the described behaviour.
- Added restriction for validation to check encumrance belong to the other ledger. Now it will filter only common rollovers
- Provided ability to search budgets from other ledgers to avoid problem with Budget not found case
[MODFISTO-426](https://issues.folio.org/browse/MODFISTO-426)
If there are breaking changes, please **STOP** and consider the …
=> [MODFISTO-426] - Unreleased encumbrances causing rollover errors

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
[MODFISTO-430](https://issues.folio.org/browse/MODFISTO-430)
There could be 2 possible error message returned for Rollover Preview in case order uses several ledgers and some of them are not rollovered yet:
1. Part of the encumbrances belong to the ledger, which has not been rollovered
2. Budget not found
Expected behaviour in this case is to always have same error(first one)
The reason why second error might be returned is that when order is checked for related not rollovered ledgers, "preview" rollovers are taken into account.
So if, let's say, order uses 2 ledgers, ledger1 and ledger2, when  rollover preview for ledger1 is called, there's `Part of the encumbrances belong to the ledger, which has not been rollovered`  error added for this order.
However rollover preview for ledger 2 …
=> MODFISTO-430 Improve error handling for test ledger rollovers where orders belong to several ledgers and calculate result budget

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
We should take into account only rollover progreseses in current fiscal year while run rollover.
- Added new condition to check of rollover fiscal year
[MODFISTO-430](https://issues.folio.org/browse/MODFISTO-430)
to …
=> [MODFISTO-430] - FY Rollover Preview fails if an order is using more than one ledger

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
To generate unique encumbrances, the stored function "uuid_generate_v5(namespace uuid, name text)" from the "uuid-ossp" module is utilized. To resolve the problem, it is proposed to ignore the encumbrance from the previous year during the insertion into the "transaction" table. This will ensure uniqueness of encumbrances within each year and prevent the duplication of primary keys in the "transaction" table during the roll-over process. Consequently, each new year will have its own distinct encumbrances, resolving the issue of transaction overflow between years.
- skip insert process on transaction talbe when happening conflict by id
[MODFISTO-441](https://issues.folio.org/browse/MODFISTO-441)
- …
=> [MODFISTO-441] - Add the ability to skip the transaction if it is from the previous year

src/main/java/org/folio/service/budget/BudgetService.java, src/main/java/org/folio/service/transactions/TransferService.java, src/test/java/org/folio/rest/impl/TransactionTest.java
Remove the limits on decreasing allocated amount.
- When fromFundId is not null and transfer type is allocation it means that decrease allocation action. Was decided to bypass the check by adding 'Allocation' type to filter in the beggining of the method
[MODFISTO-443](https://issues.folio.org/browse/MODFISTO-443)
- Did you modify code to call some …
=> [MODFISTO-443] - Allow user to decrease allocation resulting in a negative available amount

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql, src/main/resources/templates/db_scripts/schema.json, src/main/resources/templates/db_scripts/transactions.sql
Need to skip **transaction_encumbrance_idx_unique** unique index for 'transaction' table while running rollover
- `ON CONFLICT (id) DO NOTHING` replaced with 
`WHERE NOT EXISTS (
SELECT 1
FROM ${myuniversity}_${mymodule}.transaction tr
WHERE tr.id = t.id
)`
- We can't use **ON CONFLICT ON CONSTRAINT _constraint name_** because we refer to partial unique index. To resolve it was used index expression.
Probably we need to use new PostgreSQL MERGE command to upsert these modified lines more elegant. Merge command is available from 16 version of PG: https://www.postgresql.org/docs/16/sql-merge.html
[MODFISTO-461](https://folio-org.atlassian.net/browse/MODFISTO-461)
- Does this PR meet or exceed the …
=> [MODFISTO-461] - FYRO fails on duplicate encumbrance

scripts/fix_encumbrances/fix_encumbrances_quesnelia.py
[MODFISTO-469](https://folio-org.atlassian.net/browse/MODFISTO-469) - Encumbrance script: do not try to fix orderStatus for past fiscal years
- Skip the operation to fix orderStatus for past fiscal years, with a message if that option was chosen in the menu.
- Updated the menu text
- Tested logic execution locally.
- Did you modify code to call some …
=> [MODFISTO-469] Encumbrance script: do not try to fix orderStatus for past fiscal years

src/main/java/org/folio/rest/util/ErrorCodes.java, src/main/java/org/folio/service/transactions/batch/BatchTransactionChecks.java, src/test/java/org/folio/service/transactions/BatchTransactionServiceTest.java
[MODFIN-352](https://folio-org.atlassian.net/browse/MODFIN-352) - Remove the old transaction API
- Allow transaction processing for planned budgets (to create new budgets with an allocation)
- Check new payments and credits have a positive amount (check migrated from the old mod-finance transaction API)
[related mod-finance PR](https://github.com/folio-org/mod-finance/pull/245)
[related integration tests PR](https://github.com/folio-org/folio-integration-tests/pull/1320)
- Do …
=> [MODFIN-352] Allow transaction processing for planned budgets + new amount validation

src/main/resources/data/transactions/allocations-8.4.0/all_allocations.json
Currently the data initialization from samples fails with:
> org.folio.rest.exception.HttpException: Cannot process transactions because a budget is not active or planned
This is because we try to create an allocation for a closed fund.
Removed the allocation for the closed fund.
Ideally, all the PRs …
=> [MODFISTO-460] Don't create an allocation for a closed fund

src/main/java/org/folio/service/transactions/batch/BatchPaymentCreditService.java, src/main/java/org/folio/service/transactions/batch/BatchPendingPaymentService.java, src/test/java/org/folio/service/transactions/PaymentCreditTest.java, src/test/java/org/folio/service/transactions/PendingPaymentTest.java
[MODFISTO-488](https://folio-org.atlassian.net/browse/MODFISTO-488) - Wrong encumbrance when cancelling an invoice with an order that is not open
- Fixed encumbrance calculations when cancelling a pending payment, payment or credit (see ticket).
- Fixed and improved unit tests
- Checked result with the UI
[Integration tests PR](https://github.com/folio-org/folio-integration-tests/pull/1419)
- Are the JIRAs under active …
=> [MODFISTO-488] Fixed encumbrance changes after cancelling a payment or credit

src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
https://folio-org.atlassian.net/browse/MODFISTO-483
Updated budget_encumbrances_rollover.sql
- In calculate_planned_encumbrance_amount, replace jsonb->'encumbrance'->>'amountExpended' by (jsonb->'encumbrance'->>'amountExpended')::decimal - (jsonb->'encumbrance'->>'amountCredited')::decimal
- In rollover_order,  add 'amountCredited', 0, after 'amountExpended', 0,.
Add a credited variable to build_budget and set credited := (_budget->>'credits')::decimal;
- In later calculations, replace expended by expended - credited
Add the credits field to result_budget
=> [MODFISTO-483] - Add credited field support to Rollover functionality

src/main/java/org/folio/service/rollover/LedgerRolloverService.java, src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql, src/test/java/org/folio/service/rollover/LedgerRolloverServiceTest.java
- <https://folio-org.atlassian.net/browse/MODORDERS-1162>
- Remove a condition set in by this PR: [MODFISTO-298](<https://github.com/folio-org/mod-finance-storage/blob/06c18e36947ce250d7384e23edc054360b3c48b8/src/main/java/org/folio/service/rollover/LedgerRolloverService.java#L132>)
- Update encumbrance statuses in `budget_encumbrances_rollover` stored function so that the rollover can occur without any enabled settings to output `Released` encumbrance transactions with amounts equal to 0
- <https://github.com/folio-org/mod-orders/pull/1022>
- <https://github.com/folio-org/folio-integration-tests/pull/1536>
=> [MODORDERS-1162]. Order line encumbrance link not updated when re-encumber is false and order type not rolled over

pom.xml, src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
[[MODFISTO-499] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODFISTO-499)
- Update versions
- Add module descriptor validator
=> [MODFISTO-499] Update libraries of dependant acq modules to the latest versions

src/main/java/org/folio/service/transactions/batch/BatchPendingPaymentService.java
[[MODINVOICE-563] Encumbrance value incorrect after paying credit invoice](https://folio-org.atlassian.net/browse/MODINVOICE-563)
- Only update encumbrance amount if status is Unreleased
=> [MODINVOICE-563] Encumbrance value incorrect after paying credit invoice

src/main/resources/templates/db_scripts/migration/extract_credits_from_expenditures.sql
failied in run migration script
https://folio-org.atlassian.net/browse/MODFISTO-511
- used jsonb || jsonb_build_object to bypass version lock system
=> [MODFISTO-511] - Fix sql migration by using json_build_object

descriptors/ModuleDescriptor-template.json, ramls/finance-data.raml, src/main/java/org/folio/config/ServicesConfiguration.java, src/main/java/org/folio/dao/budget/BudgetDAO.java, src/main/java/org/folio/dao/budget/BudgetPostgresDAO.java, src/main/java/org/folio/dao/fund/FundDAO.java, src/main/java/org/folio/dao/fund/FundPostgresDAO.java, src/main/java/org/folio/rest/impl/FinanceDataApi.java, src/main/java/org/folio/rest/impl/FundAPI.java, src/main/java/org/folio/service/budget/BudgetService.java, src/main/java/org/folio/service/financedata/FinanceDataService.java, src/main/java/org/folio/service/fund/FundService.java, src/main/java/org/folio/service/fund/StorageFundService.java, src/main/resources/templates/db_scripts/all_finance_data_view.sql, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/rest/impl/FinanceDataApiTest.java, src/test/java/org/folio/rest/impl/TestBase.java, src/test/java/org/folio/service/fianancedata/FinanceDataServiceTest.java
https://folio-org.atlassian.net/browse/MODFISTO-501
- Implemented API to update finance data as a bulk
- Implemented API details
- Added tests
=> [MODFISTO - 501] - Implement endpoint to save FY finance data in bulk

ramls/finance-data.raml, src/main/java/org/folio/service/budget/BudgetService.java, src/main/java/org/folio/service/financedata/FinanceDataService.java, src/main/java/org/folio/service/transactions/batch/BatchTransactionService.java, src/main/resources/templates/db_scripts/all_finance_data_view.sql, src/test/java/org/folio/service/fianancedata/FinanceDataServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-381
Removed after pr https://github.com/folio-org/acq-models/pull/493#event-15559912996
updated budget batch update methods to keep original value of read only fields to avoid being set to null when budgets is being updated with fields in scope of finance data service
=> [MODFIN-381] - removed duplicate field

descriptors/ModuleDescriptor-template.json, ramls/transaction_totals.raml, src/main/java/org/folio/rest/impl/TransactionTotalApi.java, src/main/resources/templates/db_scripts/schema.json, src/main/resources/templates/db_scripts/transaction_totals_view.sql, src/test/java/org/folio/StorageTestSuite.java, src/test/java/org/folio/rest/impl/FinanceDataApiTest.java, src/test/java/org/folio/rest/impl/TransactionTest.java, src/test/java/org/folio/rest/impl/TransactionTotalApiTest.java
- <https://folio-org.atlassian.net/browse/MODFIN-391>
- Create a new view to aggregate transaction totals
- Create new API to serve the new view that aggregates transaction totals
- Karate tests in `mod-finance` and `cross-modules` folders found no regression:
=> [MODFIN-391]. Minimize amount of requests to retrieve transactions for ledger

.gitignore, scripts/fix_encumbrances/README.md, scripts/fix_encumbrances/fix_encumbrances_quesnelia.py
- [MODFISTO-417](https://folio-org.atlassian.net/browse/MODFISTO-417) - Fix encumbrances with a bad orderType
- [MODFISTO-491](https://folio-org.atlassian.net/browse/MODFISTO-491) - Fix inconsistent reEncumber values
- Added a new step to fix encumbrance properties (orderStatus, orderType, reEncumber) for open and pending orders.
- Remove more duplicate encumbrances. Previously it only checked released/unreleased duplicates; now it checks for all encumbrances with the same `orderId`/`sourcePoLineId`/`fromFundId`/`expenseClassId`/`fiscalYearId` (still in open and closed orders). Also the script tries to be smart when choosing which encumbrance to remove.
- Removed the code unreleasing encumbrances before changing order properties - this is no longer needed with the new transaction API.
- …
=> [MODFISTO-417] and [MODFISTO-491] Fix encumbrance order properties

scripts/fix_encumbrances/fix_encumbrances_quesnelia.py
Fixed syntax error for pre-3.12 python. See [PEP-701](https://docs.python.org/3.12/whatsnew/3.12.html#pep-701-syntactic-formalization-of-f-strings).
- Used different kind of quotes inside f-strings.
- Removed unused function `get_transactions_by_ids`.
Ideally, all the PRs involved in breaking changes …
=> Fixed f-string syntax for pre-3.12 python

scripts/fix_encumbrances/fix_encumbrances_quesnelia.py
[MODFISTO-514](https://folio-org.atlassian.net/browse/MODFISTO-514) - Encumbrance script: remove links to encumbrances for pending orders in an old FY
Fixed logic to select encumbrances without an active budget: take into account the budget fiscal year.
[Previous PR for MODFISTO-514](https://github.com/folio-org/mod-finance-storage/pull/444)
- Did you …
=> [MODFISTO-514] Fixed selecting encumbrances without active budget

src/main/java/org/folio/service/transactions/batch/BatchTransactionHolder.java, src/test/java/org/folio/service/transactions/EncumbranceTest.java
[MODFISTO-515](https://folio-org.atlassian.net/browse/MODFISTO-515) - Support deleting pending payments with batch transaction API
This PR fixes an issue with the [previous one](https://github.com/folio-org/mod-finance-storage/pull/465), which was causing the test for [MODORDERS-1253](https://folio-org.atlassian.net/browse/MODORDERS-1253) (`change-pending-distribution-with-inactive-budget`) to fail. The implementation for MODORDERS-1253 relies on the fact that budget activity is not checked for 0-amount encumbrances to delete.
If there are breaking changes, please **STOP** and consider the …
=> [MODFISTO-515] Do not process 0-amount encumbrances before deleting

descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/BF-1169
Use correct interface for making /orders/rollover declared in https://github.com/folio-org/mod-orders/blob/5e64ade74aaacd212eb84a98fe70c87e88f12bb3/descriptors/ModuleDescriptor-template.json#L1089C14-L1089C29
=> BF-1169. Fix incorrect interface for rollover
