- ramls/examples/budget_collection.sample
- ramls/schemas/budget.json
- ramls/schemas/fiscal_year.json
- ramls/schemas/fund.json
- ramls/schemas/fund_distribution.json
- ramls/schemas/ledger.json
- ramls/schemas/tag.json
- ramls/schemas/transaction.json
Enable upper-case in first segment.
> FOLIO-972 Improve UUID-like regex

- ramls/examples/fiscal_year.sample
- ramls/examples/fiscal_year_collection.sample
- scripts/lint-raml-cop.sh
Adds scripts/lint-raml-cop.sh for local use.
> FOLIO-1187 add scripts/lint-raml-cop.sh

- sample-data/ledgers/One-time.json
- sample-data/ledgers/Ongoing.json
Add required "code" property. Towards MODFUND-27.
> Update sample data for ledgers.

- Dockerfile
- pom.xml
Artifacts published by CI are still under the name mod-finance, though this module has been renamed.
> Update module name in pom.xml.

- NEWS.md
- pom.xml
> Release 1.0.1

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODFISTO-7 - Release mod-finance-storage-1.1.0.  
Next version should be 1.2.0-SNAPSHOT
Following all approach and best practices outlines in https://wiki.folio.org/display/FOLIJET/Acquisitions+-+Release+Procedures
> MODFISTO-7 Release 1.1.0

- src/main/resources/data/fiscal-years/fy1.json
https://issues.folio.org/browse/MODFUND-50
* Updated acq-models submodels
* Sample data updated …
> MODFUND-50 Problem with Start/End dates

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/budget.raml
- ramls/encumbrance.raml
- ramls/fiscal_year.raml
- ramls/fund.raml
- ramls/fund_distribution.raml
- ramls/ledger.raml
- ramls/transaction.raml
[MODFISTO-13](https://issues.folio.org/browse/MODFISTO-13) Create MODFISTO release
* All module interfaces and ramls versions updated to 2.0
* News updated with release details …
> MODFISTO-13 Release version 2.0.0

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODFISTO-17](https://issues.folio.org/browse/MODFISTO-17) Create MODFISTO release
* `funds` module interface version updated to 3.0
* News updated with release details
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> MODFISTO-17 - Release 3.0.0

- src/main/resources/data/fiscal-years/fy1.json
- src/main/resources/data/fiscal-years/fy18.json
- src/main/resources/data/fiscal-years/fy19.json
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/utils/TestEntities.java
[MODFISTO-25](https://issues.folio.org/browse/MODFISTO-25) Update FiscalYear schema
Updating sample data and DB table definition
> MODFISTO-25 Update FiscalYear schema

- src/main/resources/templates/db_scripts/transactions.sql
- src/test/java/org/folio/rest/impl/TransactionTest.java
* https://issues.folio.org/browse/MODFISTO-27
* Updated recalculation trigger
* Added unit test for transfers …
> MODFISTO-27 Transaction Calculations - Transfers

- src/main/resources/templates/db_scripts/transactions.sql
- src/test/java/org/folio/rest/impl/TransactionTest.java
Resolve comments:
[allocation calculations](https://issues.folio.org/browse/MODFISTO-26?focusedCommentId=62115&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-62115)
[return error if source budget does not exist](https://issues.folio.org/browse/MODFISTO-27?focusedCommentId=62109&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-62109)
- fixing allocation calculation
- return error if source budget does not exist
- Do …
> MODFISTO-26 Transaction Calculations - Allocations

- .settings/.gitignore
- src/main/resources/data/fiscal-years/fy18.json
- src/main/resources/data/fiscal-years/fy19.json
- src/main/resources/data/ledgers/MainLibrary.json
- src/main/resources/data/ledgers/One-time.json
- src/main/resources/data/ledgers/Ongoing.json
- src/test/java/org/folio/rest/impl/BudgetTest.java
- src/test/java/org/folio/rest/impl/GroupFundFYTest.java
- src/test/java/org/folio/rest/impl/LedgerFYTest.java
- src/test/java/org/folio/rest/impl/LedgerFundBudgetStatusTest.java
- src/test/java/org/folio/rest/impl/TestBase.java
https://issues.folio.org/browse/MODFISTO-49
- Following [PR#189](https://github.com/folio-org/acq-models/pull/189), sample data and unit tests need to be updated
TODO:
[PR#189](https://github.com/folio-org/acq-models/pull/189) needs to be merged first then point acq-models PR branch to master
Ideally all of the PRs involved in breaking changes would be …
> MODFISTO-49: Ledger/LedgerFY updates: Schema changes

- src/main/resources/templates/db_scripts/transactions.sql
- src/test/java/org/folio/rest/impl/TransactionTest.java
https://issues.folio.org/browse/MODFISTO-29
* Updating calculations trigger
* Creating unit tests
* Budget overEncumbered will be calculated in a follow-on story
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> MODFISTO-29 Transaction Calculations - Encumbrance

- src/main/resources/templates/db_scripts/transactions.sql
- src/test/java/org/folio/rest/impl/TransactionTest.java
https://issues.folio.org/browse/MODFISTO-52
* Updating recalculations according to [wiki](https://wiki.folio.org/display/FOLIJET/Finance+Data+Model#FinanceDataModel-Calculations)
* Updating unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> MODFISTO-52 fixed Unavailable recalculation

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/group-budgets.raml
- src/main/java/org/folio/rest/impl/GroupBudgetAPI.java
- src/main/java/org/folio/rest/impl/TenantReferenceAPI.java
- src/main/java/org/folio/rest/persist/EntitiesMetadataHolder.java
- src/main/java/org/folio/rest/persist/HelperUtils.java
- src/main/java/org/folio/rest/persist/QueryHolder.java
- src/main/resources/data/group-fund-fiscal-years/AFRICAHIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/ANZHIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/ASIAHIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/CANHIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/CANLATHIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/EUROHIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/HIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/LATAMHIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/MIDEASTHIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/MISCHIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/SLAVHIST-FY19.json
- src/main/resources/data/group-fund-fiscal-years/USHIST-FY19.json
- src/main/resources/templates/db_scripts/group_budget_view.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
- src/test/java/org/folio/rest/impl/GroupBudgetTest.java
- src/test/java/org/folio/rest/impl/GroupFundFYTest.java
- src/test/java/org/folio/rest/impl/HelperUtilsTest.java
- src/test/java/org/folio/rest/impl/StorageTestSuite.java
- src/test/java/org/folio/rest/impl/TransactionTest.java
[MODFISTO-48](https://issues.folio.org/browse/MODFISTO-48) Adjustments to allow listing budgets by group/fiscalYear/ledger
- created group_budgets_view
- added ability to search budgets by groups fields
- added  foreign key `group_fund_fiscal_years.budgetId->budget.id` to `group_fund_fiscal_years` table
Ideally all of the PRs involved in breaking changes …
> MODFISTO-48 Adjustments to allow listing budgets by group/fiscalYear/ledger

- pom.xml
- src/main/resources/data/transactions/encumbrance.json
- src/test/java/org/folio/rest/utils/TestEntities.java
https://issues.folio.org/browse/MODFISTO-54
- modify the sampleddata to match the values from other modules …
> MODFISTO-54: encumbrance schema changes

- src/main/resources/data/ledgers/MainLibrary.json
- src/main/resources/data/ledgers/One-time.json
- src/main/resources/data/ledgers/Ongoing.json
- src/main/resources/data/transactions/credit.json
- src/main/resources/data/transactions/payment.json
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/LedgerFYTest.java
- src/test/java/org/folio/rest/impl/LedgerFundBudgetStatusTest.java
- src/test/java/org/folio/rest/impl/TestBase.java
[MODFISTO-46](https://issues.folio.org/browse/MODFISTO-46)
- updating acq-models
- adding temporary_invoice_payments table
- updating sample data
Additionally:
- fixed sample data. `ledger.fiscalYearOneId` referred to non-existed fiscalYear
- added foreign key constrain on `ledger.fiscalYearOneId` to link `ledger` and `fiscal_year` tables
Ideally all of …
> MODFISTO-46 Update transaction schema

- src/main/resources/templates/db_scripts/migration/budgets.sql
- src/main/resources/templates/db_scripts/migration/fiscal_years.sql
- src/main/resources/templates/db_scripts/migration/funds.sql
- src/main/resources/templates/db_scripts/migration/ledgers.sql
- src/main/resources/templates/db_scripts/schema.json
- src/main/resources/templates/db_scripts/transactions.sql
[MODFISTO-41](https://issues.folio.org/browse/MODFISTO-41)
Instances:
- before: [original.txt](https://github.com/folio-org/mod-finance-storage/files/3744216/original.txt)
- after: [updated.txt](https://github.com/folio-org/mod-finance-storage/files/3744217/updated.txt)
data migration scripts for all breaking schema changes starting after the Q3.2 release
- Default values for currency stetted to USD at the moment.
- Are the JIRAs …
> MODFISTO-41 - Data migration scripts for recent schema changes

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/budget.raml
- ramls/fiscal-year.raml
- ramls/fund.raml
- ramls/ledger.raml
- ramls/transaction.raml
https://issues.folio.org/browse/MODFISTO-36
* Updating NEWS.md, ramls, interface version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
> MODFISTO-36 Release 4.0.0

- pom.xml
- src/main/java/org/folio/rest/persist/HelperUtils.java
- src/main/java/org/folio/rest/persist/MoneyUtils.java
- src/main/java/org/folio/rest/transaction/EncumbranceHandler.java
https://issues.folio.org/browse/MODFISTO-67
* RMB version updated to 29.1.1
* Updated libraries versions. Some dependencies were removed, because RMB already provides all required libraries
* Code updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> MODFISTO-67 RMB version updated to 29.1.1

- src/main/resources/templates/db_scripts/transactions.sql
- src/test/java/org/folio/rest/impl/TransactionTest.java
[MODFISTO-72](https://issues.folio.org/browse/MODFISTO-72) 
- removing  unavailable calculations for Transfer …
> MODFISTO-72 ledgerFY.unavailable and budget.unavailable must not change during Transfer

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
https://issues.folio.org/browse/MODFISTO-70
* updated release notes
* updated ledgers interface …
> MODFISTO-70 # preparation for bug fix release 4.0.1

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
https://issues.folio.org/browse/MODFISTO-76
Bugfix release to be included in Q4
- Bump the ledger interface version as 2 new required fields were added
- Bump the minor version to include new sample data and the schema changes
> MODFISTO-76- Release 4.1.0

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODFISTO-79
- increment the fromModuleVersion to 4.1.1
> MODFISTO-79-Release-4.1.1

- descriptors/ModuleDescriptor-template.json
- src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODFISTO-28: This is a follow on PR , the permissions for the new API were missing in the earlier one. 
- Added permissions for invoice summaries API
- As the table "temporary_invoice_payments" was renamed to temporary_invoice_transactions, adding delete, so that the table is deleted while updating to next versions
Ideally …
> MODFISTO-28: Adding permissions for invoice summary

- src/main/java/org/folio/rest/transaction/EncumbranceHandler.java
- src/main/java/org/folio/rest/transaction/PaymentCreditHandler.java
- src/test/java/org/folio/rest/impl/PaymentsCreditsTest.java
https://issues.folio.org/browse/MODFISTO-82
- Update Payments/Credits and Encumbrance to handle negative awaiting payment
- Update unit test …
> MODFISTO-82 awaitingPayment should never go below 0

- src/main/java/org/folio/rest/transaction/PaymentCreditHandler.java
- src/test/java/org/folio/rest/impl/PaymentsCreditsTest.java
https://issues.folio.org/browse/MODFISTO-81
* set budget expenditures on payments/credit
* updated unit tests …
> MODFISTO-81 Budget expenditures must be updated on payments/credit

- src/main/java/org/folio/rest/impl/FinanceStorageAPI.java
- src/main/java/org/folio/rest/transaction/AllOrNothingHandler.java
- src/main/java/org/folio/rest/transaction/EncumbranceHandler.java
- src/main/java/org/folio/rest/transaction/PaymentCreditHandler.java
- src/test/java/org/folio/rest/impl/PaymentsCreditsTest.java
- src/test/java/org/folio/rest/impl/TransactionTest.java
[MODFISTO-80](https://issues.folio.org/browse/MODFISTO-80) ledgerFY records need to be updated upon payment/credit.
- adding logic to update ledgerFY according to [wiki](https://wiki.folio.org/display/FOLIJET/Finance+Data+Model#FinanceDataModel-Calculations) …
> MODFISTO-80 LedgerFY records must be updated on payments/credits

- src/main/java/org/folio/rest/transaction/AllOrNothingHandler.java
- src/test/java/org/folio/rest/impl/PaymentsCreditsTest.java
https://issues.folio.org/browse/MODFISTO-62
* implemented payment restrictions
* unit tests updated
* It looks like there is a problem with [calculation formula](https://wiki.folio.org/display/FOLIJET/Finance+Data+Model#FinanceDataModel-TransactionRestrictions). Wait until it will be corrected
Ideally all of the PRs involved in breaking changes would be …
> MODFISTO-62 Payment restrictions

- src/main/java/org/folio/rest/transaction/AllOrNothingHandler.java
https://issues.folio.org/browse/MODFISTO-62
* calculation fixed according ti wiki
While …
> MODFISTO-62 calculation fixed

- src/main/resources/templates/db_scripts/migration/budgets.sql
- src/main/resources/templates/db_scripts/schema.json
This is follow-on to [MODFISTO-83](https://issues.folio.org/browse/MODFISTO-83). If we use `tables .uniqueIndex`  to create an index, the index is created before the "scripts.after" section.
- moved creation of unique index on budget.name from schema.json to migration/budget.sql
Ideally all of the PRs involved in breaking changes would be merged in the …
> MODFISTO-83 Create unique index after renaming duplicates

- src/main/java/org/folio/rest/transaction/InvoiceTransactionsHandler.java
- src/test/java/org/folio/rest/impl/EncumbrancesTest.java
[MODFISTO-91](https://issues.folio.org/browse/MODFISTO-91) - Budgets aren't updated correctly upon updating/releasing encumbrance
Updating an encumbrance w/ awaitingPayment which also has status Released.
Always process budget and additional process encumbrance releasing if needed in accordance to https://wiki.folio.org/pages/viewpage.action?spaceKey=FOLIJET&title=Finance+Data+Model.
- …
> MODFISTO-91 - Budgets aren't updated correctly upon updating/releasing encumbrance

- NEWS.md
- pom.xml
- ramls/transaction-summary.raml
https://issues.folio.org/browse/MODFISTO-92
Release 4.2.0
* Updated release notes
* updated transaction-summary.raml version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> MODFISTO-92 Release 4.2.0

- src/main/java/org/folio/rest/service/TransactionSummaryService.java
- src/main/java/org/folio/rest/transaction/AllOrNothingHandler.java
https://issues.folio.org/browse/MODFISTO-95
* fixed transaction summary check and update
* make summary check before creating temporary transaction
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
> MODFISTO-95 updated all or nothing handler

- src/main/java/org/folio/rest/impl/BudgetAPI.java
- src/main/java/org/folio/rest/impl/FinanceStorageAPI.java
- src/main/java/org/folio/rest/impl/FiscalYearAPI.java
- src/main/java/org/folio/rest/impl/FundAPI.java
- src/main/java/org/folio/rest/impl/LedgerAPI.java
- src/main/java/org/folio/rest/persist/CriterionBuilder.java
- src/main/java/org/folio/rest/persist/HelperUtils.java
- src/main/java/org/folio/rest/persist/Tx.java
- src/main/java/org/folio/rest/service/BudgetService.java
- src/main/java/org/folio/rest/service/TransactionSummaryService.java
- src/main/java/org/folio/rest/transaction/AllOrNothingHandler.java
- src/main/java/org/folio/rest/transaction/InvoiceTransactionsHandler.java
- src/main/java/org/folio/rest/transaction/OrderTransactionsHandler.java
- src/main/java/org/folio/rest/util/ResponseUtils.java
- src/test/java/org/folio/rest/impl/BudgetTest.java
- src/test/java/org/folio/rest/impl/TestBase.java
- src/test/java/org/folio/rest/impl/TransactionTest.java
[MODFISTO-96](https://issues.folio.org/browse/MODFISTO-96)
- retrieve budget
- look for transactions by budget.fundId and budget.fiscalYearId
- if transactions are found throw transactionIsPresentBudgetDeleteError
- in db transaction
- remove reference to budget from group_fund_fiscal_year table
- delete budget
Refactoring
- updated CriterionBuilder to support multiple criteria and operations
- moved db transaction handling from HelperUtils to Tx class
- moved logic related to response handling from HelperUtils to ResponseUtils
If there are breaking changes, please **STOP** and consider the …
> MODFISTO-96 Add logic upon budget deletion

- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-97](https://issues.folio.org/browse/MODFISTO-97) some tables were changed or deleted during Q1. However, fromModuleVersion was not updated for all db changes
Fixed from module version for:
- budget migration script
- fund_distribution table -- was deleted during bug fixing for Q12020
- transaction table -- some changes in transaction.sql
- invoice_transaction_summaries table introduced in 4.2.0
- temporary_invoice_transactions table  introduced in 4.2.0
- temporary_invoice_payments removed in 4.2.0
- What other …
> MODFISTO-97 Issues upgrading module from Edelweiss to Fameflower

- pom.xml
- src/main/java/org/folio/rest/impl/FiscalYearAPI.java
- src/main/java/org/folio/rest/impl/FundAPI.java
- src/main/java/org/folio/rest/impl/LedgerAPI.java
- src/main/java/org/folio/rest/persist/HelperUtils.java
- src/main/java/org/folio/rest/persist/Tx.java
- src/main/java/org/folio/rest/service/BudgetService.java
- src/main/java/org/folio/rest/service/TransactionSummaryService.java
- src/main/java/org/folio/rest/transaction/AllOrNothingHandler.java
- src/main/java/org/folio/rest/transaction/InvoiceTransactionsHandler.java
- src/main/java/org/folio/rest/util/ResponseUtils.java
* https://issues.folio.org/browse/MODFISTO-98
* fixed future completion
* code refactoring.
* rmb updated to 29.4.0
* vertx updated to 3.9.0 …
> MODFISTO-98 fixed future completion

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
MODFISTO-93 - Create MODFISTO Bugfix release
The primary focus of this release was to restrict processing transactions after performing "all or nothing" mechanism.
> [MODFISTO-93] - Bugfix release 4.2.1

- src/main/java/org/folio/rest/impl/FiscalYearAPI.java
- src/main/java/org/folio/rest/impl/LedgerAPI.java
- src/test/java/org/folio/rest/impl/LedgerFYTest.java
[MODFISTO-75]() - LedgerFY records for past years
We need to handle the scenario of making the ledgerFY record available for past years. 
Currently we are creating ledgerFY records for FYs where, periodEnd > now
* LedgerFY records are always created as needed (upon FY and Ledger creation)
* Unit tests are updated
Ideally all of the PRs involved in …
> MODFISTO-75 - LedgerFY records for past years

- pom.xml
- src/main/java/org/folio/rest/transaction/AllOrNothingHandler.java
- src/test/java/org/folio/rest/impl/EncumbrancesTest.java
- src/test/java/org/folio/rest/impl/PaymentsCreditsTest.java
- src/test/java/org/folio/rest/impl/TransactionTest.java
https://issues.folio.org/browse/MODFISTO-99
* implemented sequential temp transaction processing
https://vertx.io/docs/vertx-core/groovy/#_asynchronous_locks
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
> MODFISTO-99 implemented tempTransaction lock

- descriptors/ModuleDescriptor-template.json
- src/main/resources/data/transactions/credits/credit_CANHIST_30121.json
- src/main/resources/data/transactions/encumbrances/encumbrance_AFRICAHIST_306857_1.json
- src/main/resources/data/transactions/encumbrances/encumbrance_ENDOW-SUBN_S60402_80.json
- src/main/resources/data/transactions/encumbrances/encumbrance_EUHIST_313000-01_2.json
- src/main/resources/data/transactions/encumbrances/encumbrance_EUROHIST_268758-02.json
- src/main/resources/data/transactions/encumbrances/encumbrance_MISCHIST_268758-03.json
- src/main/resources/data/transactions/encumbrances/encumbrance_MISCHIST_268879_1.json
- src/main/resources/data/transactions/encumbrances/encumbrance_UNIV-SUBN_312325_1.json
- src/main/resources/data/transactions/encumbrances/encumbrance_USHIST_268758-01.json
- src/main/resources/data/transactions/encumbrances/encumbrance_USHIST_313000-01_1.json
- src/main/resources/data/transactions/encumbrances/encumbrance_USHIST_79_1.json
- src/main/resources/data/transactions/payments/payment_ENDOW-SUBN_30121.json
- src/main/resources/templates/db_scripts/migration/transaction_source_enum.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/utils/TestEntities.java
[MODFISTO-85](https://issues.folio.org/browse/MODFISTO-85) - Update the transaction 'source' enum
We need to make a few tweaks to the transaction schema, namely the "source" field enumeration.
New values:
* User
* FiscalYear
* PoLine
* Invoice
* Data migration scripts are implemented
* The `acq-models` submodule is updated
Ideally all of the PRs involved …
> MODFISTO-85 - Update the transaction 'source' enum

- src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODFISTO-78
General rule of thumb wrt indices:
fulltext (text and do not care case/accent) - makes sense for things like notes, descriptions, comments
ginIndex (text and care about case/accent) - makes sense for things like title
index (anything else) - makes sense for exact match like UUIDs, enums or booleans, numbers, etc.
* added indexes
- Do PRs exist …
> MODFISTO-78 added indexes

- descriptors/ModuleDescriptor-template.json
- ramls/transaction-summary.raml
- src/main/java/org/folio/rest/impl/TransactionSummaryAPI.java
- src/test/java/org/folio/rest/impl/TransactionsSummariesTest.java
https://issues.folio.org/browse/MODFISTO-109
PR for PUT endpoint only
* added transaction-summary PUT method …
> MODFISTO-109 added transaction-summary PUT method

- src/main/java/org/folio/service/transactions/EncumbranceAllOrNothingService.java
- src/main/java/org/folio/service/transactions/PendingPaymentAllOrNothingService.java
[MODFIN-135](https://issues.folio.org/browse/MODFIN-135)
- Update logic to calculate available field in budget …
> [MODFIN-135] Available amount drops to 0 when encumbering money

- src/main/resources/templates/db_scripts/migration/pending_payment_cross_module.ftl
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
[MODFISTO-106](https://issues.folio.org/browse/MODFISTO-106)
[MODFISTO-107](https://issues.folio.org/browse/MODFISTO-107)
- used ftl to run scripts only upon module upgrade
- added script to create pending payments from invoice lines fundDistributions
- added script to create pending payments form invoice adjustments fundDistributions
- added script to update budgets totals by amounts of created not linked to encumbrance pending payments
- added script to update ledgerFY recordstotals by amounts of created not linked to encumbrance pending payments
- added script to update invoice transaction summary records
- rename numEncumbrances to numPendingPayments
- set `-numPaymentsCredits` to numPendingPayments value 
Before merging this PR, please go through the following list and take …
> MODFISTO-107/MODFISTO-106 Data migration scripts for pending payments

- pom.xml
- src/main/java/org/folio/dao/budget/BudgetDAO.java
- src/main/java/org/folio/dao/budget/BudgetPostgresDAO.java
- src/main/java/org/folio/dao/ledgerfy/LedgerFiscalYearPostgresDAO.java
- src/main/java/org/folio/dao/transactions/BaseTemporaryTransactionsDAO.java
- src/main/java/org/folio/dao/transactions/BaseTransactionDAO.java
- src/main/java/org/folio/dao/transactions/EncumbranceDAO.java
- src/main/java/org/folio/dao/transactions/PaymentCreditDAO.java
- src/main/java/org/folio/dao/transactions/PendingPaymentDAO.java
- src/main/java/org/folio/dao/transactions/TemporaryInvoiceTransactionDAO.java
- src/main/java/org/folio/dao/transactions/TemporaryOrderTransactionDAO.java
- src/main/java/org/folio/rest/impl/FundAPI.java
- src/main/java/org/folio/rest/impl/InitAPIs.java
- src/main/java/org/folio/rest/impl/LedgerAPI.java
- src/main/java/org/folio/rest/impl/TransactionSummaryAPI.java
- src/main/java/org/folio/rest/persist/DBClient.java
- src/main/java/org/folio/rest/persist/HelperUtils.java
- src/main/java/org/folio/service/budget/BudgetService.java
- src/main/java/org/folio/service/group/GroupService.java
- src/main/java/org/folio/service/transactions/EncumbranceAllOrNothingService.java
- src/main/java/org/folio/service/transactions/PaymentCreditAllOrNothingService.java
- src/main/java/org/folio/service/transactions/PendingPaymentAllOrNothingService.java
- src/main/resources/templates/db_scripts/migration/pending_payment_cross_module.ftl
- src/main/resources/templates/db_scripts/migration/rename_ledger_fy_table.ftl
- src/main/resources/templates/db_scripts/schema.json
- src/main/resources/templates/db_scripts/transactions.sql
- src/test/java/org/folio/dao/transactions/BaseTransactionDAOTest.java
- src/test/java/org/folio/rest/impl/EncumbrancesTest.java
- src/test/java/org/folio/rest/impl/PaymentsCreditsTest.java
- src/test/java/org/folio/service/transactions/PendingPaymentAllOrNothingServiceTest.java
[MODFISTO-110](https://issues.folio.org/browse/MODFISTO-110)  Update to RMB v30.0.2
The module has been updated in accordance with the documentation https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-300
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> MODFISTO-110 mod-finance-storage: Update to RMB v30.0.2

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
[MODFISTO-108](https://issues.folio.org/browse/MODFISTO-108)
- updated NEWS
- added release notes from 4.2.2 to NEWS.md
- increased minor version for finance-storage.ledgers, finance-storage.groups, finance-storage.fiscal-years
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> MODFISTO-108 Release 5.0.0

- src/main/java/org/folio/service/transactions/EncumbranceAllOrNothingService.java
- src/test/java/org/folio/rest/impl/EncumbrancesTest.java
[MODFISTO-114](https://issues.folio.org/browse/MODFISTO-114)
- updated budgets collection fixed …
> MODFISTO-114 Ledger FY totals not updated after encumbrance update

- NEWS.md
- pom.xml
[MODFISTO-116 - Bugfix release 5.0.1](https://issues.folio.org/browse/MODFISTO-116)
- updated NEWS …
> [MODFISTO-116] - Bugfix release 5.0.1

- NEWS.md
- pom.xml
- src/main/java/org/folio/service/transactions/EncumbranceAllOrNothingService.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/EncumbrancesTest.java
[MODFISTO-116 - Bugfix release 5.0.1](https://issues.folio.org/browse/MODFISTO-116)
Merge bug fixes from master to long live branch …
> Merge bug fix release 5.0.1 from master to long live branch

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/expense_class.raml
- src/main/java/org/folio/rest/impl/ExpenseClassAPI.java
- src/main/java/org/folio/rest/impl/TenantReferenceAPI.java
- src/main/resources/data/expense-classes/elec.json
- src/main/resources/data/expense-classes/prn.json
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
- src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
- src/test/java/org/folio/rest/utils/TestEntities.java
https://issues.folio.org/browse/MODFISTO-105
* added expense class API
* added reference data …
> MODFISTO-105 added expense class API

- descriptors/ModuleDescriptor-template.json
- ramls/budget_expense_class.raml
- src/main/java/org/folio/rest/impl/BudgetExpenseClassAPI.java
- src/main/java/org/folio/rest/impl/TenantReferenceAPI.java
- src/main/resources/data/budget-expense-classes/AFRICAHIST-FY20-elec.json
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
- src/test/java/org/folio/rest/utils/TestEntities.java
[MODFISTO-115](https://issues.folio.org/browse/MODFISTO-115)
- API defined and imlemented
- DB schema defined:
- budgetId, expenseClassId unique index added
- foreign key to budget and expense_class tables added
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> MODFISTO-115 Define and implement budget-expense-classes API

- ramls/budget_expense_class.raml
- src/main/java/org/folio/dao/budget/BudgetPostgresDAO.java
[MODFIN-136](https://issues.folio.org/browse/MODFIN-136)
- update acq-models
- define expenseClassStatus in raml to generated model for this schema
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
> MODFISTO-136 Update schemas

- pom.xml
- src/main/java/org/folio/service/transactions/BaseAllOrNothingTransactionService.java
- src/main/java/org/folio/service/transactions/EncumbranceAllOrNothingService.java
- src/main/java/org/folio/service/transactions/PaymentCreditAllOrNothingService.java
- src/main/java/org/folio/service/transactions/PendingPaymentAllOrNothingService.java
- src/test/java/org/folio/service/transactions/PendingPaymentAllOrNothingServiceTest.java
[MODFISTO-125](https://issues.folio.org/browse/MODFISTO-125)
Fix calculation budget remaining amount based on different transactions type
- Add different calculation for budget remaining amount
- Update test
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
> Modfisto 125

- ramls/budget_expense_class.raml
- src/main/resources/data/budgets/AFRICAHIST-FY20.json
- src/main/resources/data/budgets/ANZHIST-FY20.json
- src/main/resources/data/budgets/ASIAHIST-FY20.json
- src/main/resources/data/budgets/CANHIST-FY20.json
- src/main/resources/data/budgets/CANLATHIST-FY20-closed.json
- src/main/resources/data/budgets/ENDOW-SUBN-FY20.json
- src/main/resources/data/budgets/EUROHIST-FY20.json
- src/main/resources/data/budgets/EXCH-SUBN-FY20.json
- src/main/resources/data/budgets/GIFT-SUBN-FY20.json
- src/main/resources/data/budgets/GIFTS-ONE-TIME-FY20.json
- src/main/resources/data/budgets/GRANT-SUBN-FY19.json
- src/main/resources/data/budgets/HIST-FY20.json
- src/main/resources/data/budgets/LATAMHIST-FY20.json
- src/main/resources/data/budgets/MIDEASTHIS-FY20.json
- src/main/resources/data/budgets/MISCHIST-FY20.json
- src/main/resources/data/budgets/ONE-TIME-SWEEP-FY20-frozen.json
- src/main/resources/data/budgets/SLAVHIST-FY18.json
- src/main/resources/data/budgets/STATE-MONOSER-FY18.json
- src/main/resources/data/budgets/STATE-SUBN-FY18.json
- src/main/resources/data/budgets/UNIV-SUBN-FY20.json
- src/main/resources/data/budgets/USHIST-FY20.json
* https://issues.folio.org/browse/MODFISTO-102
* updated acq-models
* updated samples, sorted budget fields …
> MODFISTO-102 updated acq-models

- NEWS.md
- pom.xml
- mod-finance-storage 5.0.2 hotfix release …
> Tmp release 5.0.2

- src/main/resources/templates/db_scripts/migration/fill_budget_net_transfer.sql
- src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODFIN-119
Migration script …
> [MODFIN-119] - Migration script

- NEWS.md
- pom.xml
[MODFISTO-127](https://issues.folio.org/browse/MODFISTO-127)
Update news after hotfix release …
> Modfisto 127 1

- pom.xml
- src/main/java/org/folio/service/budget/BudgetService.java
- src/main/java/org/folio/service/transactions/EncumbranceAllOrNothingService.java
- src/main/java/org/folio/service/transactions/PaymentCreditAllOrNothingService.java
- src/main/java/org/folio/service/transactions/PendingPaymentAllOrNothingService.java
- src/main/java/org/folio/service/transactions/TransferService.java
[MODFISTO-140](https://issues.folio.org/browse/MODFISTO-140)
Composite orders web API updates budget objects with invalid date updated values
- Update metadata date once we change budget totals
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
> Modfisto 140

- descriptors/ModuleDescriptor-template.json
- ramls/transaction-summary.raml
- src/main/java/org/folio/dao/transactions/BaseTransactionDAO.java
- src/main/java/org/folio/dao/transactions/TransactionDAO.java
- src/main/java/org/folio/rest/impl/TransactionSummaryAPI.java
- src/main/java/org/folio/service/transactions/PendingPaymentService.java
- src/main/java/org/folio/service/transactions/TransferService.java
- src/test/java/org/folio/service/transactions/PendingPaymentServiceTest.java
[MODFISTO-138](https://issues.folio.org/browse/MODFISTO-138)
- implemented allOrNothing for Pending payment update
- create "fake" Pending payment based on transactions from storage with amount = newAmount - amountFromStorage
- process "fake" Pending payment as real upon creation
- update Pending payment from storage by new ones
- defined and implemented PUT /finance-storage/invoice-transaction-summaries/{id} API
to be able update numPendingPayments
Additionally fixed TransferService.createTransaction
- What other modules …
> MODFISTO-138 Update PUT /finance-storage/transactions/id to support allOrNothing for Pending payments

- src/main/java/org/folio/dao/transactions/TemporaryInvoiceTransactionDAO.java
- src/main/java/org/folio/dao/transactions/TemporaryOrderTransactionDAO.java
- src/main/java/org/folio/rest/impl/ExpenseClassAPI.java
- src/main/java/org/folio/rest/impl/FiscalYearAPI.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/dao/transactions/PendingPaymentDAOTest.java
[MODFISTO-165](https://issues.folio.org/browse/MODFISTO-165) …
> MODFISTO-165 Field "expenseClassId" must be a part of unique-constraint

- Dockerfile
- Jenkinsfile
- pom.xml
- src/main/java/org/folio/rest/impl/InitAPIs.java
- src/test/java/org/folio/rest/impl/HelperUtilsTest.java
https://issues.folio.org/browse/MODFISTO-132
* updated RMB v31.1.1 …
> MODFISTO-132 RMB v31.1.1

- src/main/resources/templates/db_scripts/migration/update_processed_order_transaction_summary.sql
- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-94](https://issues.folio.org/browse/MODFISTO-94)
- added migration script to update numTransactons for processed order_transaction_summary records
- migration of invoice_transaction_summary records  covered by pending_payment_cross_module.ftl script …
> MODFISTO-94 Migration script for performed transactions

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-130](https://issues.folio.org/browse/MODFISTO-130) …
> MODFISTO-130 - Release 6.0.0

- src/main/java/org/folio/service/transactions/PaymentCreditService.java
- src/main/java/org/folio/service/transactions/PendingPaymentService.java
- src/test/java/org/folio/service/transactions/PendingPaymentServiceTest.java
[MODFISTO-183](https://issues.folio.org/browse/MODFISTO-183)
- calculate encumbrance awaiting payment value even if it being released …
> MODFISTO-183 Awaiting payment value in encumbrance not updated correctly

- pom.xml
https://issues.folio.org/browse/MODFISTO-182
* rmb 31.1.5 …
> MODFISTO-182 rmb 31.1.5

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODFISTO-179
* updated release notes …
> MODFISTO-179 release 6.0.1

- NEWS.md
> MODFISTO-179 release 6.0.1 news.md -> master

- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-175](https://issues.folio.org/browse/MODFISTO-175) …
> MODFISTO-175 Define model and schema for the errors of the ledger fiscal year rollover

- descriptors/ModuleDescriptor-template.json
- ramls/ledger_rollover_progress.raml
- src/main/java/org/folio/rest/impl/LedgerRolloverProgressAPI.java
- src/test/java/org/folio/StorageTestSuite.java
- src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
- src/test/java/org/folio/rest/utils/TestEntities.java
- src/test/resources/data/ledger-fiscal-year-rollovers/main-library-progress.json
https://issues.folio.org/browse/MODFISTO-168
1. New ledger rollover progress API created
2. Unit tests added  …
> [MODFISTO-168] - Define storage API for retrieving rollover status

- descriptors/ModuleDescriptor-template.json
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com> …
> MODFISTO-163 Define storage API for the ledger fiscal year rollover

- src/main/resources/templates/db_scripts/migration/update_order_encumbrance.sql
- src/main/resources/templates/db_scripts/schema.json
Create migration script for setting in all encumbrances "reEncumber" = true > https://issues.folio.org/browse/MODFISTO-177
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> Modfisto 177

- src/main/resources/templates/db_scripts/migration/update_budget_summary_information.sql
https://issues.folio.org/browse/MODFISTO-190
- fix order by for initial allocation
While …
> MODFISTO-190 Migration : Fill new fields of the Budget schema with new Financial information

- src/main/resources/data/budgets/SLAVHIST-FY18.json
- src/main/resources/data/budgets/STATE-MONOSER-FY18.json
- src/main/resources/data/budgets/STATE-SUBN-FY18.json
- src/main/resources/data/budgets/UNIV-SUBN-FY20.json
- src/main/resources/data/budgets/USHIST-FY20.json
[MODFISTO-188](https://issues.folio.org/browse/MODFISTO-188) Update Ledger schema with new Financial information
[MODFISTO-197](https://issues.folio.org/browse/MODFISTO-197) Adjust fiscal year schema with financial summary model)
[MODFISTO-203](https://issues.folio.org/browse/MODFISTO-203) Update group-fiscal-year schema with new Financial information) …
> MODFISTO-188/MODFISTO-197/MODFISTO-203 Update schemas with new Financial information

- src/main/resources/templates/db_scripts/migration/pending_payment_cross_module.ftl
> Fix typo in migration script

- src/main/java/org/folio/utils/CalculationUtils.java
- src/test/java/org/folio/StorageTestSuite.java
- src/test/java/org/folio/utils/CalculationUtilsTest.java
[MODFISTO-211](https://issues.folio.org/browse/MODFISTO-211) …
> MODFISTO-211 Incorrect budget overExpended value

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
[MODFISTO-210](https://issues.folio.org/browse/MODFISTO-210)
Allow user to intentionally reset budget allowances during rollover
- Update rollover.sql to handle empty allowable values
- Update acq-model to make allowable values optional
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> Modfisto 210 1

- src/main/java/org/folio/service/transactions/restriction/EncumbranceRestrictionService.java
- src/main/java/org/folio/service/transactions/restriction/PaymentCreditRestrictionService.java
- src/main/java/org/folio/service/transactions/restriction/PendingPaymentRestrictionService.java
- src/test/java/org/folio/StorageTestSuite.java
- src/test/java/org/folio/service/transactions/restriction/EncumbranceRestrictionServiceTest.java
- src/test/java/org/folio/service/transactions/restriction/PaymentCreditRestrictionServiceTest.java
- src/test/java/org/folio/service/transactions/restriction/PendingPaymentRestrictionServiceTest.java
[MODFISTO-206](https://issues.folio.org/browse/MODFISTO-206)
- Changed calculation for EncumbranceRestrictionService.getBudgetRemainingAmount(), removing "-(allocated - (unavailable + available))" from the result.
- Clarified calculation using variables defined in MODFISTO-206.
- Updated PaymentCreditRestrictionService and PendingPaymentRestrictionService for consistency, but without changing the calculation.
- Improved the related test in PendingPaymentRestrictionServiceTest.
- Added EncumbranceRestrictionServiceTest and PaymentCreditRestrictionServiceTest, but only testing the related method.
@folio-org/acquisitions
- Does this …
> [MODFISTO-206] Changed calculation for EncumbranceRestrictionService.getBudgetRemainingAmount()

- src/main/java/org/folio/rest/util/ErrorCodes.java
- src/main/java/org/folio/service/transactions/AllocationService.java
- src/main/java/org/folio/utils/CalculationUtils.java
- src/test/java/org/folio/StorageTestSuite.java
- src/test/java/org/folio/rest/impl/TestBase.java
- src/test/java/org/folio/rest/impl/TransactionTest.java
- src/test/java/org/folio/service/transactions/AllocationServiceTest.java
- src/test/java/org/folio/service/transactions/PendingPaymentServiceTest.java
[MODFISTO-216](https://issues.folio.org/browse/MODFISTO-216)
- allow to create allocation with empty `toFundId` field
- add verification that at least one from `toFundId` or 'fromFundId' fields populated
- do not allow to set non-positive value to transaction amount
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
> MODFISTO-216 Ensure Increase and decrease in allocation are always positive values

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
[MODFISTO-220](https://issues.folio.org/browse/MODFISTO-220)
Funds lose group assignments after fiscal year rollover
- Update rollover script to create group relations if exist …
> [MODFISTO-220] Funds lose group assignments after fiscal year rollover

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
https://issues.folio.org/browse/MODFISTO-224
* retrieve encumbrances from fromFiscalYear by sourcePoLineId
* calculate related fundDistribution percentage value: fundDistrValue= fromFiscalYearEncumbrance/sum(transactions.encmbrance.initialAmountEncumbered)
* calculate po line cost for toFiscalYear:
* oldPoLineTotal = encumbraceRollover.basedOn == remaining ? sum(transactions.amount):  sum(transactions.encumnrance.amountExpended)
* newPoLineTotal = oldPoLineTotal + (encumbraceRollover.increasedBy * oldPoLineTotal/100)
* encumbrance amount for toFiscalYear = newPoLineTotal * fundDistrValue
If there …
> MODFISTO-224 Calculate transaction amount based on fundDistribution percentage value

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-193] - Release 7.0.0
While it's helpful for reviewers to help identify …
> [MODFISTO-193] - Release 7.0.0

- NEWS.md
- PERSONAL_DATA_DISCLOSURE.md
- PERSONAL_DATA_DISCLOSURE.md.txt
> [MODFISTO-201] -  Add personal data disclosure form

- src/main/resources/templates/db_scripts/migration/pending_payment_cross_module.ftl
[MODFISTO-213](https://issues.folio.org/browse/MODFISTO-213)
Added a test for the existence of the table in the migration script. …
> [MODFISTO-213] Migrating ledgerfy only if the table exists

- NEWS.md
- pom.xml
Bugfix 7.0.1 
While it's helpful for reviewers to help identify potential problems, …
> [MODFISTO-230] - Bugfix 7.0.1

- src/main/resources/templates/db_scripts/schema.json
Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com> …
> [MODFISTO-234] Unable to complete fiscal year rollover

- src/main/java/org/folio/service/transactions/AllOrNothingTransactionService.java
- src/main/java/org/folio/service/transactions/EncumbranceService.java
- src/test/java/org/folio/rest/impl/EncumbrancesTest.java
[MODFISTO-233](https://issues.folio.org/browse/MODFISTO-233)
In the case Released -> Unreleased:
- Added exceptions to the tests preventing a change to released encumbrance
- Changed the transaction amount to initialAmountEncumbered, and updated the budget's encumbered property
- Added a verification that the encumbrance's amountExpended is 0
- Added unit tests
- Unit tests fail with a confusing error message when a Vagrant VM is up (possibly a port conflict?)
- Do JIRAs exist …
> [MODFISTO-233] Added support for encumbrance status change from Released to Unreleased

- NEWS.md
- pom.xml
> [MODFISTO-241] MODFISTO (mod-finance-storage) Hotfix #1 release

- NEWS.md
- src/main/resources/templates/db_scripts/migration/update_encumbrances_order_status.ftl
- src/main/resources/templates/db_scripts/schema.json
Sync news.md and Updated migration script from release branch
> MODFISTO-237 Sync news.md and Updated migration script from release branch

- src/main/resources/templates/db_scripts/transactions.sql
[MODFISTO-231](https://issues.folio.org/browse/MODFISTO-231)
Issue with database migration for Iris release
- remove trigger function via migration
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
> [MODFISTO-231] Issue with database migration for Iris release

- pom.xml
- src/test/java/org/folio/StorageTestSuite.java
- src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
- src/test/java/org/folio/rest/impl/HelperUtilsTest.java
- src/test/java/org/folio/utils/CalculationUtilsTest.java
https://issues.folio.org/browse/MODFISTO-227
* fixed testcontainer usage
While it's …
> MODFISTO-227 update rmb 33.0.0

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODFISTO-226
* updated release notes …
> MODFISTO-226 release 7.1.0

- NEWS.md
- pom.xml
Bugfix release 7.0.4
While it's helpful for reviewers to help identify potential …
> [MODFISTO-248] - Bugfix release 7.0.4

- NEWS.md
- pom.xml
[MODFISTO-253](https://issues.folio.org/browse/MODFISTO-253)
Checked inclusion of needed PR and updated NEWS.md. …
> [MODFISTO-253] Hotfix 7.0.5

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-247](https://issues.folio.org/browse/MODFISTO-247)
(this is not a release PR, it is just including changes for MODFISTO-247 into the R2 long-lived branch)
Included all commits for MODFISTO-247.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> [MODFISTO-247] Rollover errors when at least 1 order has encumbrance with initialAllocation = 0

- NEWS.md
- pom.xml
[MODFISTO-250](https://issues.folio.org/browse/MODFISTO-250) R2 Bugfix release
Updated NEWS.md.
The fix for [MODFISTO-247](https://issues.folio.org/browse/MODFISTO-247) is already included in the 7.1 long-lived branch.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> [MODFISTO-250] R2 Bugfix release 7.1.1

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/resources/templates/db_scripts/migration/restrictions_for_fund_and_ec_codes.sql
- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-244](https://issues.folio.org/browse/MODFISTO-244) - Add validation for special character to Fund Code and Expense class code and prepare migration script
- Updated acq-models with the new restrictions
- Added a migration script to convert codes
- Incremented the API version for expense classes
Ideally all of the PRs involved in breaking …
> [MODFISTO-244] New restrictions for fund and expense class codes

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODFISTO-264 …
> Release 8.0.0 Kiwi

- src/main/java/org/folio/service/budget/BudgetService.java
Planned budgets without transactions should be deleted
While it's helpful for reviewers …
> MODFISTO-270 Delete planned budget without transactions

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
- src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODFISTO-269
Updated function calculate_planned_encumbrance_amount(_transaction jsonb, _rollover_record jsonb, _rounding boolean) to be able to base encumbrance on "Initial encumbrance" during rollover
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> MODFISTO-269. Allow user to base encumbrance on "Initial encumbrance" during rollover

- pom.xml
https://issues.folio.org/browse/MODFISTO-275 …
> MODFISTO-275 Kiwi R3 2021 - Log4j vulnerability verification and correction

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODFISTO-278 …
> MODFISTO-278 Kiwi Hotfix 8.0.2

- pom.xml
https://issues.folio.org/browse/MODFISTO-276 …
> MODFISTO-276. Juniper R2 2021 - Log4j vulnerability verification and correction

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODFISTO-277 …
> MODFISTO-277. Juniper R2 2021 HF #5 module release

- src/main/java/org/folio/service/transactions/PendingPaymentService.java
[MODFISTO-280](https://issues.folio.org/browse/MODFISTO-280) - Budget encumbrance calculation can be wrong with negative pending payments
Sorted pending payments by amount to make sure negative amounts are processed first. Before that the budget encumbrance new value was depending on the processing order of the pending payments.
Ideally all of the PRs …
> [MODFISTO-280] Process negative pending payments first

- src/main/java/org/folio/utils/CalculationUtils.java
- src/test/java/org/folio/utils/CalculationUtilsTest.java
https://issues.folio.org/browse/MODFISTO-283
Logic updated with new requirements from Jira ticket …
> [MODFISTO-283] - Over encumbrance calculation not aligned with encumbrance limit calculation

- NEWS.md
- pom.xml
https://issues.folio.org/browse/MODFISTO-288
* updated release notes …
> MODFISTO-288 Lotus 2022 R1 module release 8.1.0

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/dao/transactions/BaseTemporaryTransactionsDAO.java
- src/main/java/org/folio/rest/util/ResponseUtils.java
- src/main/java/org/folio/service/expence/ExpenseClassService.java
- src/main/java/org/folio/service/group/GroupService.java
- src/main/java/org/folio/service/transactions/AllocationService.java
- src/main/java/org/folio/service/transactions/TransferService.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/dao/transactions/PendingPaymentDAOTest.java
- src/test/java/org/folio/rest/impl/BudgetTest.java
- src/test/java/org/folio/rest/impl/EncumbrancesTest.java
- src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
- src/test/java/org/folio/rest/impl/LedgerFundBudgetStatusTest.java
- src/test/java/org/folio/rest/impl/TransactionTest.java
- src/test/java/org/folio/rest/utils/TestEntities.java
[MODFISTO-303](https://issues.folio.org/browse/MODFISTO-303) - Enable optimistic locking
- Enabled optimistic locking for the selected tables
- Updated the schemas
- Increased API major versions
- Changed error reporting to report a 409 in case of a conflict
- Made sure a record returned from a POST will have version 1
- Temporary transactions are using the version given in the request
- Updated unit tests
There are other related PRs in other modules. They should all be merged together.
- What other modules will these changes …
> [MODFISTO-303] enabled optimistic locking

- src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODFISTO-309
Changed schema.json to update rollover script when migrating to 8.2.0
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> MODFISTO-309 - Update rollover script when migrating to 8.2.0

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
https://issues.folio.org/browse/MODFISTO-311
Added ledger id to select statement used in rollover transfer creation.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> MODFISTO-311 - Only create rollover transfer for current ledger

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
https://issues.folio.org/browse/MODFISTO-311?focusedCommentId=132246&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-132246
Reverted change to rollover transactions ID generation that was made to avoid collisions. It should no longer be needed after adding ledger id to the query.
Ideally all of the PRs involved in breaking …
> MODFISTO-311 - revert transaction id generation change

- src/main/java/org/folio/rest/util/ResponseUtils.java
- src/main/java/org/folio/service/budget/BudgetService.java
- src/main/java/org/folio/service/transactions/AllocationService.java
- src/main/java/org/folio/service/transactions/EncumbranceService.java
- src/main/java/org/folio/service/transactions/PaymentCreditService.java
- src/main/java/org/folio/service/transactions/PendingPaymentService.java
- src/main/java/org/folio/service/transactions/TransferService.java
- src/main/java/org/folio/service/transactions/cancel/CancelTransactionService.java
- src/test/java/org/folio/service/transactions/AllocationServiceTest.java
- src/test/java/org/folio/service/transactions/PendingPaymentServiceTest.java
[MODFISTO-304](https://issues.folio.org/browse/MODFISTO-304) - Lock budgets to update totals
- Whenever budgets are selected and updated, changed queries to use "FOR UPDATE" to lock the selected budget rows for the Postgres transaction. A subquery was used for queries using DISTINCT, as it cannot be used at the same time as FOR UPDATE.
- Checked that Postgres transactions are always used, and rolled back in case of failure.
- Updated unit tests.
- "FOR UPDATE" can use "OF tableAlias" to specify the table to use for row locks in case a JOIN is used.
If there are breaking changes, please **STOP** and …
> [MODFISTO-304] Lock budgets to update totals

- src/main/java/org/folio/service/transactions/TransferService.java
> [MODFIN-250]-updated TransferService

- pom.xml
- src/main/java/org/folio/rest/impl/TenantReferenceAPI.java
https://issues.folio.org/browse/MODFISTO-313
* jackson version downgrade
* sample data loading fix …
> MODFISTO-313 sample data loading fix

- NEWS.md
- pom.xml
* https://issues.folio.org/browse/MODFISTO-312
* release notes updated
While it's …
> MODFISTO-312 Morning Glory R2 2022 v8.2.0 release notes

- src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODFISTO-324
*  improved search speed by adding required indexes
No need to update fromModuleVersion since RMB rebuilds indexes despite this value …
> MODFISTO-324 improved search speed by adding required indexes

- pom.xml
Version for Nolana in master should be 18.3.0-SNAPSHOT
> Fix maven version for Nolana development iteration

- src/main/resources/templates/db_scripts/schema.json
1. New table "ledger_fiscal_year_rollover_budget" added since 8.3.0
2. Unique Index "ledgerId_fromFiscalYearId" removed since 8.3.0. Validation will be done in the code
3. Acq model updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
> [MODFISTO-319] - Define schemas and table for storing generated Budgets and schema for showing rollover logs

- src/main/resources/templates/db_scripts/schema.json
> [MODFISTO-319] - Remove unique index

- NEWS.md
- src/main/resources/templates/db_scripts/schema.json
Prepare changes for Morning Glory 2022 release bug fix 2
> [MODFISTO-332] - Prepare changes for Morning Glory 2022 release bug fix 2

- scripts/fix_lotus_encumbrances/fix_lotus_encumbrances.py
https://issues.folio.org/browse/MODFISTO-329
* migrate python script to the async approach
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
> MODFISTO-329 migrate python script to the async approach

- scripts/fix_lotus_encumbrances/fix_lotus_encumbrances.py
- src/main/java/org/folio/dao/transactions/BaseTemporaryTransactionsDAO.java
- src/main/java/org/folio/service/expence/ExpenseClassService.java
- src/main/java/org/folio/service/group/GroupService.java
- src/main/java/org/folio/service/transactions/AllocationService.java
- src/main/java/org/folio/service/transactions/TransferService.java
- src/test/java/org/folio/rest/impl/EntitiesCrudTest.java
- src/test/java/org/folio/rest/impl/TransactionTest.java
- src/test/java/org/folio/rest/utils/TestEntities.java
https://issues.folio.org/browse/MODFISTO-337
Invalid usage of optimistic locking mechainsm prevents to update record without specified `_version` field. According to RMB documentation it should be handled automaticaly by specific trigger function.
https://github.com/folio-org/raml-module-builder#optimistic-locking
* removed manual handling of version number from the code
* fixed tests
* minor adjustments in python script
- Are the …
> MODFISTO-337 fixed optimistic locking usage

- pom.xml
In the [ticket](https://issues.folio.org/browse/RMB-932) was described problem with matching undefined or empty values. CQL2PgJSON tool worked incorrectly before fix. Issue affects our allocationTo and allocationFrom calculating logic.
- Upgraded RMB version
[MODFIN-272](https://issues.folio.org/browse/MODFIN-272)
[RMB-932](https://issues.folio.org/browse/RMB-932)
- Do PRs exist for …
> [MODFIN-272] Increase/decrease in allocation amounts for funds related to the same ledger are displayed in ledger Financial summary

- src/test/java/org/folio/rest/impl/LedgerRolloverBudgetTest.java
- src/test/java/org/folio/rest/impl/TenantSampleDataTest.java
- src/test/java/org/folio/rest/utils/TenantApiTestUtil.java
Due to BeforeAll code returning before completed which in turn makes following test fail.
> Fix test failing MODFISTO-344

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
https://issues.folio.org/browse/MODFISTO-318
> [MODFIN-318]. Fix issues with duplicate ids for Preview rollover

- src/main/java/org/folio/service/rollover/RolloverValidationService.java
- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
https://issues.folio.org/browse/MODFISTO-318
Fix validation query for uniqueness to be able to run Commit rollover after couple of Preview rollovers for the same ledger and fiscal year ids
> Modfisto 318 fixes

- pom.xml
Upgrade RAML Module Builder
While it's helpful for reviewers to help identify potential …
> [MODFISTO-353] - Upgraded RAML Module Builder

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
https://issues.folio.org/browse/MODFISTO-354 
There are 3 different issues/improvements performed
1. Reset field 'encumbered' to 0 in new table rollover_budget before rollover starts to be able to run multiple Preview rollovers without accumulating values for this field, because in Rollover logic there is UPDATE statement that acuumaultes field 'encumbered' each time when rollover running that is not needed, because results of preview rollovers should not be changed if invoking multiple times with the same params.
Fields 'available', 'unavailable', 'overEncumbrance' also will be updated based on 'encumbered' later in the flow in java code by CalculationUtils class.
2. Improve performance of rollover script by updating queries for budgets to use foreign keys fields that are indexed instead …
> [MODFISTO-354]. Encumbered amount is increased by the next test rollover Encumbered amount when run test rollover multiple times

- pom.xml
- src/test/java/org/folio/dao/rollover/RolloverBudgetDAOTest.java
- src/test/java/org/folio/service/rollover/RolloverValidationServiceTest.java
* https://issues.folio.org/browse/MODFISTO-353
* RMB v35.0.1 upgrade …
> MODFISTO-353 RMB v35.0.1 upgrade

- src/main/java/org/folio/config/RestClientsConfiguration.java
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/models/EmailEntity.java
- src/main/java/org/folio/rest/core/RestClient.java
- src/main/java/org/folio/service/email/EmailService.java
- src/main/java/org/folio/service/rollover/LedgerRolloverService.java
- src/main/java/org/folio/utils/EmailOkapiClient.java
- src/test/java/org/folio/StorageTestSuite.java
- src/test/java/org/folio/rest/core/RestClientTest.java
- src/test/java/org/folio/service/email/EmailServiceTest.java
- src/test/java/org/folio/service/rollover/LedgerRolloverServiceTest.java
Implement sending email and include it in the preview ledger rollover flow
While it's …
> [MODFISTO-335] - Implement sending email

- NEWS.md
- pom.xml
> [MODFISTO-356] - Release 8.3.0

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
- src/main/resources/templates/db_scripts/schema.json
Rollover fails when fund contains current and planned budgets
- Inserted planned budgets into ledger_fiscal_year_rollover_budget table to avoid incorrect error sums calculation
- Added condition by ledgerRolloverId to places where used  ledger_fiscal_year_rollover_budget  table to avoid reuse previous results of  the table
[MODFISTO-359](https://issues.folio.org/browse/MODFISTO-359)
- Do …
> [MODFISTO-359] - Rollover fails when fund contains "Planned budget" created by user

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-360](https://issues.folio.org/browse/MODFISTO-360) …
> [MODFISTO-360] - Release 8.3.1

- scripts/fix_lotus_encumbrances/README.md
- scripts/fix_lotus_encumbrances/fix_lotus_encumbrances.py
* https://issues.folio.org/browse/MODFISTO-350
* added python script with encumbrance relations fix …
> MODFISTO-350 added python script with encumbrance relations fix

- pom.xml
> [MODFIN-291]-updated version

- src/main/java/org/folio/service/budget/BudgetService.java
- src/main/java/org/folio/utils/CalculationUtils.java
- src/test/java/org/folio/rest/impl/TransactionTest.java
https://issues.folio.org/browse/MODFISTO-290
- removed [CalculationUtils.java#L55](https://github.com/folio-org/mod-finance-storage/blob/a18a4335fd1f33285dbcee1ad591e12f3198158b/src/main/java/org/folio/utils/CalculationUtils.java#L55).
- updated unit tests
- updated karate tests
Ideally, all the PRs …
> [MODFISTO-290] - Allowing "Available" to be a negative number

- src/main/java/org/folio/rest/util/ErrorCodes.java
- src/main/java/org/folio/service/budget/BudgetService.java
- src/test/java/org/folio/rest/impl/EncumbrancesTest.java
- src/test/java/org/folio/rest/impl/TransactionTest.java
https://issues.folio.org/browse/UIF-429
Introduced budgetNotFoundForTransaction error Code to avoid genericError …
> [UIF-429] - Introducing error code for scenario

- scripts/fix_lotus_encumbrances/fix_lotus_encumbrances.py
[MODFISTO-367](https://issues.folio.org/browse/MODFISTO-367) - Encumbrance script: avoid requesting too many orders at once
Implemented a new function to get orders by chunks.
TODO: [MODORDERS-832](https://issues.folio.org/browse/MODORDERS-832) - Bad error handling when too many orders are requested …
> [MODFISTO-367] Encumbrance script: get orders by chunks

- src/main/java/org/folio/service/email/EmailService.java
- src/main/java/org/folio/service/rollover/LedgerRolloverService.java
- src/main/java/org/folio/service/rollover/RolloverValidationService.java
- src/test/java/org/folio/service/email/EmailServiceTest.java
- src/test/java/org/folio/service/rollover/LedgerRolloverServiceTest.java
- src/test/java/org/folio/service/rollover/RolloverValidationServiceTest.java
[MODORDERS-834](https://issues.folio.org/browse/MODORDERS-834)
especially as the number of inter-module and …
> [MODORDERS-834] Updated acq-models reference

- scripts/fix_lotus_encumbrances/fix_lotus_encumbrances.py
[MODFISTO-368](https://issues.folio.org/browse/MODFISTO-368) - Encumbrance script: fix negative encumbrances
Fixed:
- Negative encumbrances caused by [MODORDERS-833](https://issues.folio.org/browse/MODORDERS-833).
- Bad path to `finance-storage/transactions`
- Getting the asyncio event loop
- Case with no open order or no closed order
- Display issues with the progress bar
Also switched all the code to f-strings
TODO: test in a real environment.
- Do JIRAs exist to update the …
> [MODFISTO-368] Fixed negative encumbrances and bad API path

- scripts/fix_lotus_encumbrances/README.md
[MODFISTO-368](https://issues.folio.org/browse/MODFISTO-368) - Encumbrance script: fix negative encumbrances
Updated the script's README.
Communication is paramount if …
> [MODFISTO-368] Updated the script README

- .editorconfig
- scripts/fix_lotus_encumbrances/README.md
- scripts/fix_lotus_encumbrances/fix_lotus_encumbrances.py
[MODFISTO-375](https://issues.folio.org/browse/MODFISTO-375) - Update encumbrance script to remove duplicate encumbrances
- Process all orders independently
- Get all encumbrances for the order and find duplicates
- Remove the Unreleased encumbrance, keep the Released one
- Update the encumbrance link in the po line
Note: when 2 invoices are used, one of the invoice lines might end up with a bad encumbrance link. The link gets updated without an error when the invoice is approved.
- What other modules will these changes …
> [MODFISTO-375] Remove duplicate encumbrances

- scripts/fix_lotus_encumbrances/fix_lotus_encumbrances.py
[MODFISTO-378](https://issues.folio.org/browse/MODFISTO-378) - Encumbrance script: misc fixes
- Fixed a bug when `remove_duplicate_encumbrances_in_order()` is called with no encumbrance,
- Added more type checking to avoid the previous error in the future.
- Calling transaction updates for the same order sequentially to work around [MODFISTO-377](https://issues.folio.org/browse/MODFISTO-377).
- Fixed `get_by_chunks()` (it was missing orders previously).
- Fixed a bug when summing values for budgets in `recalculate_budget_encumbered()`.
- Removed unused functions.
If there are breaking changes, …
> [MODFISTO-378] Encumbrance script fixes

- .editorconfig
- scripts/fix_lotus_encumbrances/README.md
- scripts/fix_lotus_encumbrances/fix_lotus_encumbrances.py
- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
- src/main/resources/templates/db_scripts/migration/update_budget_rollover.sql
- src/main/resources/templates/db_scripts/schema.json
Add migration script to support cache balance changes
Provide ability to calculate amounts by cash balance
[Link to karate](https://github.com/folio-org/folio-integration-tests/pull/859)
- Added migration script from boolean value to enum
- Updated calculation for net transfers amount for new budget
[MODFISTO-371](https://issues.folio.org/browse/MODFISTO-371)
[MODFISTO-373](https://issues.folio.org/browse/MODFISTO-373)
- Are the …
> [MODFISTO-371, MODFISTO-373] - Implemented Rollover Cash Balance During FYRO feature

- src/main/java/org/folio/rest/exception/HttpException.java
- src/main/java/org/folio/rest/util/ErrorCodes.java
- src/main/java/org/folio/service/transactions/PendingPaymentService.java
- src/test/java/org/folio/service/transactions/PendingPaymentServiceTest.java
[MODFISTO-384](https://issues.folio.org/browse/MODFISTO-384) - Failed to create pending payment during invoice approval
- Added a check for a null budget to make troubleshooting easier in the future.
- Added a unit test.
- [MODFISTO-385](https://issues.folio.org/browse/MODFISTO-385) - Fix encumbrances' fromFundId in the encumbrance script
- [MODINVOICE-302](https://issues.folio.org/browse/MODINVOICE-302) - Improve backend error reporting by including cause in error message systematically
- What other modules will these …
> [MODFISTO-384] New error to ease troubleshooting

- NEWS.md
- pom.xml
> [MODFISTO-379] - Release v8.4.0

- scripts/fix_encumbrances/README.md
- scripts/fix_encumbrances/fix_encumbrances.py
[MODFISTO-382](https://issues.folio.org/browse/MODFISTO-382) - Interactive menu for encumbrance script
- Added the interactive menu
- Avoid getting open or closed order list if it is not needed
- Some cleanup and minor improvements
- Renamed the script and directory to reflect the new direction
- Updated the README
- The `asyncio` module should not be installed for recent versions of python (it is meant for an old version).
- Whenever possible, it is better to use the high-level `asyncio.run()` function than setting the event loop manually.
If there are breaking changes, please **STOP** and consider …
> [MODFISTO-382] Interactive menu for encumbrance script

- scripts/fix_encumbrances/README.md
- scripts/fix_encumbrances/fix_encumbrances.py
[MODFISTO-385](https://issues.folio.org/browse/MODFISTO-385) - Fix encumbrances' fromFundId in the encumbrance script
- Added the fix within `fix_poline_encumbrances_relations()` as planned
- Optimized the whole `fix_poline_encumbrances_relations()` operation for speed by retrieving the order encumbrances before processing lines
- Did not optimize updating encumbrances by gathering the updates by order id because these new fixes are supposed to be rare
- The new fix should happen before the other one (fixing the encumbrance links) because that other one is checking `fromFundId` in the encumbrances
- Handle the case of duplicate encumbrances when it's possible to fix, print a warning if there are remaining duplicates with the right fund or if a manual fix is needed.
- Minor cleanup
- …
> [MODFISTO-385] Fix encumbrance fromFundId

- scripts/fix_encumbrances/README.md
- scripts/fix_encumbrances/fix_encumbrances.py
[MODFISTO-419](https://issues.folio.org/browse/MODFISTO-419) - Add dry-run mode to FYRO script
- Added the dry-run option at the beginning as suggested in the ticket.
- Simply modified put and delete requests to take dry-run into account, so the execution and output are the same in dry-run and normal modes, except for the actual modifications.
- Added a caveat about running all fixes with dry-run mode.
- Added more printed details of fixes (even without using dry-run, it doesn't hurt).
- Some minor cleanup.
- Unrelated bug fix in `fix_poline_encumbrances_relations()`
- Updated the README, and added documentation about saving the output in a file.
- Does this PR meet or exceed the expected quality …
> [MODFISTO-419] Added dry-run option

- scripts/fix_encumbrances/README.md
- scripts/fix_encumbrances/fix_encumbrances.py
[MODFISTO-383](https://issues.folio.org/browse/MODFISTO-383) - Encumbrance script: release encumbrances for cancelled POLs
- Added a new operation to release order line encumbrances when `paymentStatus` is `Cancelled`.
- Simple code reorganization for consistency.
- Updated the README.
Ideally, all …
> [MODFISTO-383] Release cancelled po line encumbrances

- src/main/java/org/folio/service/rollover/LedgerRolloverService.java
Need to rewrite orders rollover in an asynchronous way to avoid issues with socket conection timeout while processing rollover.
- Removed calculation overall rollover progress after starting orders rollover. 
[MODORDERS-865](https://issues.folio.org/browse/MODORDERS-865)
Ideally, all the PRs involved …
> [MODORDERS-865] Rewrite the orders rollover interaction in an asynchronous way

- NEWS.md
- pom.xml
- src/main/java/org/folio/service/rollover/LedgerRolloverService.java
> [MODFISTO-420] - Release v8.4.1

- scripts/fix_encumbrances/fix_encumbrances.py
[MODFISTO-422](https://issues.folio.org/browse/MODFISTO-422) - Fix encumbrance script when using a past fiscal year
Disabled fixing encumbrance links when the given fiscal year is not current.
to avoid breaking the …
> [MODFISTO-422] Disabled fixing encumbrance links for past FY

- src/main/java/org/folio/dao/budget/BudgetDAO.java
- src/main/java/org/folio/dao/budget/BudgetPostgresDAO.java
- src/main/java/org/folio/rest/util/ResponseUtils.java
- src/main/java/org/folio/service/budget/BudgetService.java
- src/main/java/org/folio/service/transactions/AllOrNothingTransactionService.java
- src/main/java/org/folio/service/transactions/AllocationService.java
- src/main/java/org/folio/service/transactions/TransferService.java
- src/main/java/org/folio/service/transactions/restriction/BaseTransactionRestrictionService.java
- src/main/java/org/folio/service/transactions/restriction/EncumbranceRestrictionService.java
- src/main/java/org/folio/service/transactions/restriction/PaymentCreditRestrictionService.java
- src/main/java/org/folio/service/transactions/restriction/PendingPaymentRestrictionService.java
- src/main/java/org/folio/service/transactions/restriction/TransactionRestrictionService.java
- src/test/java/org/folio/service/transactions/restriction/PendingPaymentRestrictionServiceTest.java
Invalid usage of DB transactons for Allocation transactions
* process all operation of creating allocation and transfers withing single db transaction
* fixed validation error handling
* minor code refactoring
to avoid …
> MODFISTO-421 Invalid usage of DB transactons for Allocation transactions

- src/main/java/org/folio/rest/util/ErrorCodes.java
- src/main/java/org/folio/rest/util/ResponseUtils.java
- src/main/java/org/folio/service/transactions/AllOrNothingTransactionService.java
- src/main/java/org/folio/service/transactions/restriction/BaseTransactionRestrictionService.java
- src/test/java/org/folio/rest/impl/EncumbrancesTest.java
> [MODFISTO-405] - error response processing

- scripts/fix_encumbrances/fix_encumbrances.py
[MODFISTO-427](https://issues.folio.org/browse/MODFISTO-427) - Encumbrance script: update budgets with no encumbrance
Get all budgets for the given fiscal year to initialize encumbered calculations instead of relying on encumbrances.
No change for updates (we could further optimize since we are getting the budgets before, but it is not necessary and it might be safer to do the PUT right after the GET for each budget).
- Are the …
> [MODFISTO-427] Update budgets without encumbrance if needed

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
- src/main/resources/templates/db_scripts/schema.json
> [MODFISTO-426] - Release v8.4.2

- scripts/post_order_rollover/README.md
- scripts/post_order_rollover/post_order_rollover.js
> Post order rollover script

- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-439](https://issues.folio.org/browse/MODFISTO-439)
Btree indexes were added for encumbrance.sourcePurchaseOrderId, encumbrance.sourcePoLineId in scope of this change https://github.com/folio-org/mod-finance-storage/pull/364/files#diff-4db9b6a16c40e8569cf1f57856808c27dff44495be574ae83559974077c193e4R419. They cover existing cases for search by this ids using cql queries:
`10:20:40 [323298/orders;674030/finance;667892/finance-storage] [mobius] [ff96b580-4206-4957-8b5d-7bdbc3d192f9] [mod_finance_storage] INFO CQL2PgJSON index transaction.jsonb->'encumbrance'->>'sourcePurchaseOrderId' generated SQL CASE WHEN length(lower(f_unaccent('fec354eb-14b2-4ff1-bf62-f248f073d444'))) <= 600 THEN left(lower(f_unaccent(transaction.jsonb->'encumbrance'->>'sourcePurchaseOrderId')),600) LIKE …
> MODFISTO-439 remove gin indexes for encumbrance.sourcePurchaseOrderId and encumbrance.sourcePoLineId

- src/main/java/org/folio/utils/CalculationUtils.java
- src/test/java/org/folio/utils/CalculationUtilsTest.java
[MODFISTO-442](https://issues.folio.org/browse/MODFISTO-442) - Incorrect ledger summary calculation after allocation movement to 0 budget
When the initial allocation is 0, moving the allocation added this value to the initial allocation, but should add to the allocationTo.
Ideally, all the PRs …
> [MODFISTO-442] - Incorrect ledger summary calculation

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
https://issues.folio.org/browse/MODFIN-337
Update sql schema to add other details of fund object to fund details object
Communication is paramount if that is to be …
> [MODFIN - 337] - Add locationIds to fund schema

- src/main/java/org/folio/rest/util/ErrorCodes.java
- src/main/java/org/folio/service/budget/BudgetService.java
> [MODFISTO-452] - Error message contains wrong fund name when moving allocation

- pom.xml
- src/main/java/org/folio/utils/EmailOkapiClient.java
- src/test/java/org/folio/rest/impl/HelperUtilsTest.java
https://issues.folio.org/browse/MODFISTO-447
especially as the number of inter-module and inter-team dependencies …
> [MODFISTO-447] - Update RMB to 45.1.0 and vertx to the latest version

- scripts/fix_encumbrances/README.md
- scripts/fix_encumbrances/fix_encumbrances_quesnelia.py
[MODFISTO-462](https://folio-org.atlassian.net/browse/MODFISTO-462) - Update the encumbrance script to use the new transaction API
New script for Quesnelia, updated README.
Tested manually for some cases.
to avoid …
> [MODFISTO-462] New encumbrance script for the new transaction API

- NEWS.md
- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-461](https://folio-org.atlassian.net/browse/MODFISTO-461)
especially as the number of inter-module and …
> [MODFISTO-461] - Release v8.5.1

- src/main/java/org/folio/service/transactions/batch/BatchTransactionChecks.java
[MODFISTO-472](https://folio-org.atlassian.net/browse/MODFISTO-472) - Change restricted expenditures calculations
- Changed calculation for restricted expenditures
- No change needed for unit tests
[Related integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1276)
Ideally, …
> [MODFISTO-472] Changed restricted expenditures calculation

- pom.xml
- src/test/java/org/folio/rest/core/RestClientTest.java
https://folio-org.atlassian.net/browse/MODFISTO-470
Inspired by: https://github.com/folio-org/raml-module-builder/pull/1146
> [MODFISTO-470] Upgrade RAML Module Builder

- pom.xml
- src/main/java/org/folio/config/ServicesConfiguration.java
Upgrade to https://github.com/folio-org/folio-di-support/releases/tag/v2.1.0 that has the latest Q versions
> MODFISTO-470. Upgrade folio-di-support

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODFISTO-476
> MODFISTO-476. Quesnelia module release

- src/main/resources/templates/db_scripts/budget_encumbrances_rollover.sql
- src/main/resources/templates/db_scripts/schema.json
The main purpose of the PR is avoiding issue when editing orders in Open status which has disabled flag reEncumer and refers to encumbrances from past fiscal years after rollover.
- In case of reEncumber flag is false will be created encumbrance with zero amount and Released status
[MODFISTO-477](https://folio-org.atlassian.net/browse/MODFISTO-477)
- Did …
> [MODFISTO-477] - A new encumbrance is needed during FYRO for orders with "Re-encumber" = false

- src/main/resources/templates/db_scripts/schema.json
[MODFISTO-480](https://folio-org.atlassian.net/browse/MODFISTO-480) - Old tables are not deleted
See ticket …
> [MODFISTO-480] RMB bug workaround to delete tables

- src/main/java/org/folio/utils/CalculationUtils.java
- src/test/java/org/folio/utils/CalculationUtilsTest.java
[MODFISTO-484](https://folio-org.atlassian.net/browse/MODFISTO-484) - Wrong budget overEncumbrance calculation
- Applied the new calculation
- Fixed unit tests
[Related integration tests PR](https://github.com/folio-org/folio-integration-tests/pull/1401)
Ideally, all the PRs involved in breaking …
> [MODFISTO-484] Fixed overEncumbrance calculation

- src/main/java/org/folio/service/PostgresFunctionExecutionService.java
- src/test/java/org/folio/service/PostgresFunctionExecutionServiceTest.java
https://folio-org.atlassian.net/browse/MODFISTO-487
especially as the number of inter-module and inter-team …
> [MODFISTO-487] - prevent sql injection for budget_encumbrance_rollover script

- descriptors/ModuleDescriptor-template.json
- scripts/fix_encumbrances/README.md
> MODFISTO-489 clean up permissions

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODFISTO-505
Prepare for Ramsons release
> MODFISTO-505. Prepare for Ramsons release

- src/main/resources/templates/db_scripts/schema.json
Increase version of fund update logs
> [MODFIST-497] - Increase version of fund update logs

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODFISTO-508
> MODFISTO-508. Missing interface dependencies in module descriptor

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Release Ramsons 8.7.1 Bugfix release that includes:
https://folio-org.atlassian.net/browse/MODFISTO-508
> Release Ramsons 8.7.1 Bug Fix

- NEWS.md
- pom.xml
- src/main/java/org/folio/service/transactions/batch/BatchPendingPaymentService.java
- src/main/resources/templates/db_scripts/migration/extract_credits_from_expenditures.sql
> Bug Fix Release v8.7.2

- src/main/resources/templates/db_scripts/migration/extract_credits_from_expenditures.sql
https://folio-org.atlassian.net/browse/MODFISTO-511
- use jsonb_set to avoid duplication
- make sql script produce the same result after multiple run
> [MODFISTO-511] - Update script to avoid duplication issue

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/migration/extract_credits_from_expenditures.sql
> Bug Fix Release v8.7.3

- src/main/java/org/folio/service/financedata/FinanceDataService.java
- src/main/resources/templates/db_scripts/all_finance_data_view.sql
- src/test/java/org/folio/rest/impl/FinanceDataApiTest.java
- src/test/java/org/folio/service/fianancedata/FinanceDataServiceTest.java
[MODFIN-402](https://folio-org.atlassian.net/browse/MODFIN-402) - Update current budget value and display budget records in appropriate fiscal year in downloaded .csv allocations
- Fixed the view to use the ledger's `fiscalYearOneId` and the fiscal year `series` into account (the ledger is linked to a whole series, not always a single fiscal year)
- Fixed the view's joins to not return other fiscal years but return a result even when there is no matching budget or group
- Added `budgetCurrentAllocation`
- Added support for updating the fund status
- Fixed unit tests
Related PRs: [mod-finance](https://github.com/folio-org/mod-finance/pull/272), [integration test](https://github.com/folio-org/folio-integration-tests/pull/1690)
Before merging this PR, please go through the following list and …
> [MODFIN-402] Fixes to finance data endpoint

- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/rest/exception/HttpException.java
- src/main/java/org/folio/rest/impl/FinanceDataApi.java
- src/main/java/org/folio/rest/util/ErrorCodes.java
- src/main/java/org/folio/service/financedata/FinanceDataService.java
- src/main/java/org/folio/service/fiscalyear/FiscalYearService.java
- src/main/java/org/folio/service/transactions/batch/BatchTransactionService.java
- src/test/java/org/folio/service/fianancedata/FinanceDataServiceTest.java
- src/test/java/org/folio/service/transactions/AllocationTransferTest.java
- src/test/java/org/folio/service/transactions/EncumbranceTest.java
- src/test/java/org/folio/service/transactions/PaymentCreditTest.java
- src/test/java/org/folio/service/transactions/PendingPaymentTest.java
[MODFIN-407](https://folio-org.atlassian.net/browse/MODFIN-407) - Make fund active when creating or increasing allocation
- Moved allocation creation from mod-finance to mod-finance-storage
- Updated batch transaction service to allow use as part of a larger all-or-nothing operation
- Turned finance data update into an all-or-nothing operation
- New error codes
- Creating or increasing an allocation will make the fund `Active`
- Fixed a bug in `FinanceDataApi` (errors were not returned)
- Test updates
[mod-finance PR](https://github.com/folio-org/mod-finance/pull/273), [integration test PR
](https://github.com/folio-org/folio-integration-tests/pull/1698)
- Does this PR meet or exceed the expected …
> [MODFIN-407] Make fund active with allocation, all-or-nothing finance data

- src/main/java/org/folio/service/financedata/FinanceDataService.java
- src/test/java/org/folio/rest/impl/FinanceDataApiTest.java
- src/test/java/org/folio/service/fianancedata/FinanceDataServiceTest.java
https://folio-org.atlassian.net/browse/MODFIN-403
especially as the number of inter-module and inter-team …
> [MODFIN - 403] - Improve Bulk Fund Updates validation

- src/main/java/org/folio/config/DAOConfiguration.java
- src/main/java/org/folio/config/ServicesConfiguration.java
- src/main/java/org/folio/dao/budget/BudgetDAO.java
- src/main/java/org/folio/dao/budget/BudgetPostgresDAO.java
- src/main/java/org/folio/dao/group/GroupDAO.java
- src/main/java/org/folio/dao/group/GroupPostgresDAO.java
- src/main/java/org/folio/rest/impl/BudgetAPI.java
- src/main/java/org/folio/rest/impl/GroupAPI.java
- src/main/java/org/folio/service/budget/BudgetService.java
- src/main/java/org/folio/service/financedata/FinanceDataService.java
- src/main/java/org/folio/service/group/GroupService.java
- src/test/java/org/folio/StorageTestSuite.java
- src/test/java/org/folio/service/ServiceTestUtils.java
- src/test/java/org/folio/service/budget/BudgetServiceTest.java
- src/test/java/org/folio/service/fianancedata/FinanceDataServiceTest.java
- src/test/java/org/folio/service/financedata/FinanceDataServiceTest.java
- src/test/java/org/folio/service/group/GroupServiceTest.java
- src/test/java/org/folio/service/transactions/AllocationTransferTest.java
- src/test/java/org/folio/service/transactions/BatchTransactionServiceTestBase.java
- src/test/java/org/folio/service/transactions/EncumbranceTest.java
- src/test/java/org/folio/service/transactions/PaymentCreditTest.java
- src/test/java/org/folio/service/transactions/PendingPaymentTest.java
[MODFISTO-517](https://folio-org.atlassian.net/browse/MODFISTO-517) - Create budget when adding batch allocation to fund without budget
- Create budgets as a first step, whenever an allocation or a status is added to a non-existing budget
- Budget updates and allocations happen afterwards, as before
- Getting the fiscal year only once (assumed to be the same in all data)
- Update group-fund-fiscal-year automatically when creating a budget
- Created a DAO layer for groups
- Updated unit tests
[mod-finance PR](https://github.com/folio-org/mod-finance/pull/275), [integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1704)
- Does this PR meet or exceed the expected quality …
> [MODFISTO-517] Create budgets with batch allocations

- src/main/resources/templates/db_scripts/all_finance_data_view.sql
[MODFIN-412](https://folio-org.atlassian.net/browse/MODFIN-412) - Only one row for unique budget should be displayed in batch allocation form after rollover
Fixed the finance data view to take the fiscal year into account for `group_fund_fiscal_year`.
Ideally, all the PRs involved in breaking changes …
> [MODFIN-412] Fixed finance data multiple lines with groups

- src/main/resources/templates/db_scripts/schema.json
> Add fullTextIndex to jobDetail in order to support search api

- src/test/resources/data/fund-update-log/monthly-fund-update.json
- <https://folio-org.atlassian.net/browse/MODFIN-416>
- Update acquisition models with new required fields
- Update test mocks
> [MODFIN-416]. Batch allocation logs - restrict by acq units

- src/main/resources/templates/db_scripts/create_job_number_table.sql
- src/test/java/org/folio/rest/impl/FinanceDataApiTest.java
currently jobnumber is starting from 2, it should be start from 1
- https://folio-org.atlassian.net/browse/MODFIN-415
- make first jobNumber is 0 to make it start from 1
- fix random failed test
to avoid breaking the …
> [MODFIN-415] - Make job_number start from 1

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODFISTO-521
especially as the number of inter-module and inter-team …
> Release v8.8.0

- src/main/resources/templates/db_scripts/schema.json
[MODINVOICE-586](https://folio-org.atlassian.net/browse/MODINVOICE-586) - Error when cancelling a paid invoice with 2 invoice-level adjustments using the same fund and expense class
Removed the payment and credit unique indices.
[integration test PR](https://github.com/folio-org/folio-integration-tests/pull/1816)
- Did you modify code to call some …
> [MODINVOICE-586] Remove the payment and credit indices

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
Release v8.8.2 that includes fix for https://folio-org.atlassian.net/browse/MODFISTO-525
> Release Sunflower v8.8.2

- src/main/java/org/folio/service/exchangerate/ExchangeRateSourceService.java
- src/test/java/org/folio/service/exchangerate/ExchangeRateSourceServiceTest.java
- src/test/resources/data/exchange-rate/exchange-rate-source.json
- <https://folio-org.atlassian.net/browse/MODFIN-410>
- Update Exchange Rate Source validation
- Update acq-models
> [MODFIN-410]. Integrate alternate exchange rate provider into Exchange Rate API

- src/main/resources/data/budgets-8.4.0/AFRICAHIST-FY25.json
- src/main/resources/data/transactions/allocations-8.4.0/all_allocations.json
- src/test/java/org/folio/rest/impl/BudgetTest.java
- src/test/java/org/folio/rest/impl/TestBase.java
- src/test/java/org/folio/rest/utils/TestEntities.java
- Update reference budget and transaction allocation to use for fiscal year 2025
- Add a new budget for fiscal year 2025
- Add a new transaction to allocate funds for the new budget
> Update reference budget allocation to use the new FY2025 uuid
